### ISSUE TITLE
ConjunctionSearcher panics when using keyword analyzer

### ISSUE THREAD

**Issue by zyro** [blevesearch/bleve#1074]
I'm trying to understand why the snippet below causes a panic.

```go
package main

import (
	"github.com/blevesearch/bleve"
	"github.com/blevesearch/bleve/analysis/analyzer/keyword"
	"log"
)

func main() {
	mapping := bleve.NewIndexMapping()
	mapping.DefaultAnalyzer = keyword.Name
	index, err := bleve.NewMemOnly(mapping)
	if err != nil {
		log.Fatal("failed to create index index", err)
	}

	query := bleve.NewQueryStringQuery("foo:bar +baz:\"\"")
	search := bleve.NewSearchRequest(query)

	// Line below will panic.
	_, _ = index.Search(search)

	log.Fatal("should not get this far")
}
```

Results in:
```
panic: runtime error: index out of range

goroutine 1 [running]:
testapp/vendor/github.com/blevesearch/bleve/search/searcher.(*ConjunctionSearcher).Next(0xc0000c0600, 0xc0000be390, 0xc0000a1920, 0xc0000eb750, 0x1418f0b)
	/go/src/testapp/vendor/github.com/blevesearch/bleve/search/searcher/search_conjunction.go:161 +0x524
testapp/vendor/github.com/blevesearch/bleve/search/searcher.(*PhraseSearcher).advanceNextMust(0xc0001a2380, 0xc0000be390, 0xc0001a2400, 0x0)
	/go/src/testapp/vendor/github.com/blevesearch/bleve/search/searcher/search_phrase.go:169 +0x4b
testapp/vendor/github.com/blevesearch/bleve/search/searcher.(*PhraseSearcher).initSearchers(0xc0001a2380, 0xc0000be390, 0x8, 0xc0000c4be0)
	/go/src/testapp/vendor/github.com/blevesearch/bleve/search/searcher/search_phrase.go:153 +0x35
testapp/vendor/github.com/blevesearch/bleve/search/searcher.(*PhraseSearcher).Next(0xc0001a2380, 0xc0000be390, 0x203000, 0x203000, 0x50)
	/go/src/testapp/vendor/github.com/blevesearch/bleve/search/searcher/search_phrase.go:188 +0xf6
testapp/vendor/github.com/blevesearch/bleve/search/searcher.(*ConjunctionSearcher).initSearchers(0xc0000c0660, 0xc0000be390, 0x14daf80, 0xc0000e2401)
	/go/src/testapp/vendor/github.com/blevesearch/bleve/search/searcher/search_conjunction.go:128 +0x97
testapp/vendor/github.com/blevesearch/bleve/search/searcher.(*ConjunctionSearcher).Next(0xc0000c0660, 0xc0000be390, 0x196f740, 0x1296129, 0x1d00d80)
	/go/src/testapp/vendor/github.com/blevesearch/bleve/search/searcher/search_conjunction.go:153 +0x4bb
testapp/vendor/github.com/blevesearch/bleve/search/searcher.(*BooleanSearcher).initSearchers(0xc0000e24d0, 0xc0000be390, 0x14dabc0, 0xc0000eb940)
	/go/src/testapp/vendor/github.com/blevesearch/bleve/search/searcher/search_boolean.go:118 +0x5a
testapp/vendor/github.com/blevesearch/bleve/search/searcher.(*BooleanSearcher).Next(0xc0000e24d0, 0xc0000be390, 0x0, 0x0, 0x15bf540)
	/go/src/testapp/vendor/github.com/blevesearch/bleve/search/searcher/search_boolean.go:211 +0x892
testapp/vendor/github.com/blevesearch/bleve/search/collector.(*TopNCollector).Collect(0xc0002c01c0, 0x15c3920, 0xc0000b4040, 0x15c6000, 0xc0000e24d0, 0x15c7380, 0xc0002d6020, 0xc0000e24d0, 0x0)
	/go/src/testapp/vendor/github.com/blevesearch/bleve/search/collector/topn.go:161 +0x221
testapp/vendor/github.com/blevesearch/bleve.(*indexImpl).SearchInContext(0xc0001981c0, 0x15c3920, 0xc0000b4040, 0xc000198690, 0x0, 0x0, 0x0)
	/go/src/testapp/vendor/github.com/blevesearch/bleve/index_impl.go:517 +0xda4
testapp/vendor/github.com/blevesearch/bleve.(*indexImpl).Search(0xc0001981c0, 0xc000198690, 0x15c75c0, 0xc0001981c0, 0x0)
	/go/src/testapp/vendor/github.com/blevesearch/bleve/index_impl.go:368 +0x4d
main.main()
	/go/src/testapp/main.go:21 +0x1ff
```

This happens reliably under Go 1.11.2 and Bleve 9b6e89951d4e9207356a833a7d99577cfe249208. It seems to panic here: https://github.com/blevesearch/bleve/blob/9b6e89951d4e9207356a833a7d99577cfe249208/search/searcher/search_conjunction.go#L161

It's not reproducible for all queries that return no results, only when odd terms like `+baz:\"\"` are present but I would not expect an improper query to result in a panic.

**Comment by abhinavdangeti** [comment]
Hmm, looks to me like we need to add a protective if-clause above the for loop in the case the query_string initializes a conjunction searcher with no searchers within it.
