### ISSUE TITLE
scorch - index out of range - concurrent query

### ISSUE THREAD

**Issue by peleteiro** [blevesearch/bleve#1259]
When querying and index concurrently (using wrk to test) scorch panics.

```
panic: runtime error: index out of range

goroutine 100 [running]:
github.com/blevesearch/bleve/index/scorch/segment/zap.(*docValueIterator).loadDvChunk(0xc00036a070, 0x0, 0x87, 0xc00037e0d0, 0xc000102b01, 0x1)
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index/scorch/segment/zap/docvalues.go:123 +0x4cd
github.com/blevesearch/bleve/index/scorch/segment/zap.(*SegmentBase).VisitDocumentFieldTerms(0xc00037e0d0, 0x87, 0xc0005881a0, 0x2, 0x2, 0xc0003b0210, 0x0, 0x0)
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index/scorch/segment/zap/docvalues.go:189 +0x181
github.com/blevesearch/bleve/index/scorch.(*IndexSnapshot).DocumentVisitFieldTerms(0xc0000fc540, 0xc00043e4f0, 0x8, 0x8, 0xc0005881a0, 0x2, 0x2, 0xc0003b0210, 0x1, 0xc0003b0210)
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index/scorch/snapshot_index.go:425 +0x3c5
github.com/blevesearch/bleve/index/scorch.(*Reader).DocumentVisitFieldTerms(0xc0000fa150, 0xc00043e4f0, 0x8, 0x8, 0xc0005881a0, 0x2, 0x2, 0xc0003b0210, 0xc00067a0a8, 0xc00043b078)
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index/scorch/reader.go:61 +0x84
github.com/blevesearch/bleve/search/collector.(*TopNCollector).visitFieldTerms(0xc00064c8f0, 0xad0d60, 0xc0000fa150, 0xc00043b100, 0x0, 0x0)
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/blevesearch/bleve@v0.7.0/search/collector/topn.go:226 +0xc8
github.com/blevesearch/bleve/search/collector.(*TopNCollector).collectSingle(0xc00064c8f0, 0xc0000fa238, 0xad0d60, 0xc0000fa150, 0xc00043b100, 0x0, 0x0)
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/blevesearch/bleve@v0.7.0/search/collector/topn.go:160 +0x771
github.com/blevesearch/bleve/search/collector.(*TopNCollector).Collect(0xc00064c8f0, 0xac9900, 0xc0000f6078, 0xacdd40, 0xc0007261e0, 0xad0d60, 0xc0000fa150, 0x2, 0x0)
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/blevesearch/bleve@v0.7.0/search/collector/topn.go:133 +0x213
github.com/blevesearch/bleve.(*indexImpl).SearchInContext(0xc00036a000, 0xac9900, 0xc0000f6078, 0xc0004c45b0, 0x0, 0x0, 0x0)
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index_impl.go:432 +0x10c2
github.com/blevesearch/bleve.(*indexImpl).Search(0xc00036a000, 0xc0004c45b0, 0xa08416, 0x9, 0xc00064c640)
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/blevesearch/bleve@v0.7.0/index_impl.go:363 +0x4e
main.Search(0xc0005a4500)
	/home/peleteiro/Projects/biblebox/search/cmd/server.go:77 +0x4d2
github.com/fasthttp/router.(*Router).Handler(0xc0003945d0, 0xc0005a4500)
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/fasthttp/router@v0.3.4/router.go:303 +0xfbf
github.com/valyala/fasthttp.(*Server).serveConn(0xc00010eb60, 0xacdbc0, 0xc000425180, 0x0, 0x0)
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/valyala/fasthttp@v1.3.0/server.go:1958 +0x630
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0001d23f0, 0xc00042c360)
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/valyala/fasthttp@v1.3.0/workerpool.go:212 +0xc0
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0001d23f0, 0xc00042c360, 0x9299c0, 0xc00042c360)
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/valyala/fasthttp@v1.3.0/workerpool.go:184 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/home/peleteiro/.asdf/installs/golang/1.12.5/packages/pkg/mod/github.com/valyala/fasthttp@v1.3.0/workerpool.go:183 +0x119
```

**Comment by mschoch** [comment]
Version 0.7 is now over a year old, and there is a good chance we have already addressed this.

I'd recommend you try using master until another release can be made.

**Comment by peleteiro** [comment]
You are right! It worked smoothly using master.

Thanks a lot
