### ISSUE TITLE
Crash in bleve v0.7.0

### ISSUE THREAD

**Issue by tmm1** [blevesearch/bleve#1272]
I encountered the following crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xb2af56]

goroutine 47 [running]:
github.com/blevesearch/bleve/index/upsidedown.(*TermFrequencyRow).ValueSize(0xc001a24c48, 0x83e80000d)
	github.com/blevesearch/bleve@v0.7.0/index/upsidedown/row.go:465 +0x16
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).batchRows(0xc0004ec200, 0x1a3dfc0, 0xc0001f2020, 0xc002e73000, 0x1f9, 0x200, 0xc0022f0000, 0x1fb, 0x200, 0xc00415e000, ...)
	github.com/blevesearch/bleve@v0.7.0/index/upsidedown/upsidedown.go:189 +0x1495
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch(0xc0004ec200, 0xc000406000, 0xc0001045f8, 0x0)
	github.com/blevesearch/bleve@v0.7.0/index/upsidedown/upsidedown.go:938 +0x1262
github.com/blevesearch/bleve.(*indexImpl).Batch(0xc0001045b0, 0xc000491fa0, 0x0, 0x0)
	github.com/blevesearch/bleve@v0.7.0/index_impl.go:304 +0x9a
```

I am in the process of upgrading to bleve master, so maybe this is already fixed since I know v0.7.0 is quite old now.

**Comment by mschoch** [comment]
It's unlikely anything has been fixed, no one is working on upsidedown any more.

**Comment by tmm1** [comment]
Looks like there was an error from leveldb earlier during the indexing process: `Corruption: bad entry in block`

So I'm guessing the underlying corruption surfaced up somehow and caused bleve to crash on a nil TermFrequencyRow.

**Comment by mschoch** [comment]
Getting nil pointer here:

https://github.com/blevesearch/bleve/blob/1a319cdf5bf77dc8cee35a6b99f908792c2547ef/index/upsidedown/row.go#L465

Would seem to indicate that `tfr` was nil, as `tfr.vectors` being nil would simply be a noop for range.

It is strange, hard to see how one of the rows we're processing became nil.  And, it's hard to see how a previous leveldb error would cause this, since I don't think this operation has attempted to write anything yet, it's still preparing the data to be written...

**Comment by tmm1** [comment]
I tried to delete and recreate the index from scratch on the same node, and ran into an even stranger issue:

```
runtime: VirtualAlloc of 86935339008 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw(0x17beeeb, 0xd)
        go/src/runtime/panic.go:617 +0x79
runtime.sysMap(0xc009400000, 0x143dc00000, 0x25b08f8)
        go/src/runtime/mem_windows.go:122 +0x138
runtime.(*mheap).sysAlloc(0x2590640, 0x143dafa000, 0x2590650, 0xa1ed7d)
        go/src/runtime/malloc.go:633 +0x1d4
runtime.(*mheap).grow(0x2590640, 0xa1ed7d, 0x0)
        go/src/runtime/mheap.go:1222 +0x49
runtime.(*mheap).allocSpanLocked(0x2590640, 0xa1ed7d, 0x25b0908, 0x0)
        go/src/runtime/mheap.go:1150 +0x3a9
runtime.(*mheap).alloc_m(0x2590640, 0xa1ed7d, 0x101, 0x0)
        go/src/runtime/mheap.go:977 +0xd0
runtime.(*mheap).alloc.func1()
        go/src/runtime/mheap.go:1048 +0x53
runtime.(*mheap).alloc(0x2590640, 0xa1ed7d, 0x7010101, 0x429497)
        go/src/runtime/mheap.go:1047 +0x91
runtime.largeAlloc(0x143daf9d56, 0x450101, 0xc002bfe000)
        go/src/runtime/malloc.go:1055 +0xa0
runtime.mallocgc.func1()
        go/src/runtime/malloc.go:950 +0x4d
runtime.systemstack(0x0)
        go/src/runtime/asm_amd64.s:351 +0x6b
runtime.mstart()
        go/src/runtime/proc.go:1153

goroutine 70 [running]:
runtime.systemstack_switch()
        go/src/runtime/asm_amd64.s:311 fp=0xc002b8afe0 sp=0xc002b8afd8 pc=0x45db00
runtime.mallocgc(0x143daf9d56, 0x1587b40, 0x1, 0xc002c22de0)
        go/src/runtime/malloc.go:949 +0x8b1 fp=0xc002b8b080 sp=0xc002b8afe0 pc=0x40e131
runtime.makeslice(0x1587b40, 0x143daf9d56, 0x143daf9d56, 0x9)
        go/src/runtime/slice.go:49 +0x73 fp=0xc002b8b0b0 sp=0xc002b8b080 pc=0x446173
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).batchRows(0xc001e3cc80, 0x1a4daa0, 0xc007176080, 0xc00033c000, 0x6a, 0x80, 0xc0008e4300, 0xb, 0x10, 0x0, ...)
        github.com/blevesearch/bleve@v0.7.0/index/upsidedown/upsidedown.go:172 +0x19c0 fp=0xc002b8b5a0 sp=0xc002b8b0b0 pc=0xb331d0
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch(0xc001e3cc80, 0xc001e34fe0, 0xc00038b628, 0x0)
        github.com/blevesearch/bleve@v0.7.0/index/upsidedown/upsidedown.go:938 +0x1262 fp=0xc002b8ba58 sp=0xc002b8b5a0 pc=0xb39332
github.com/blevesearch/bleve.(*indexImpl).Batch(0xc00038b5e0, 0xc000fb34e0, 0x0, 0x0)
        github.com/blevesearch/bleve@v0.7.0/index_impl.go:304 +0x9a fp=0xc002b8ba88 sp=0xc002b8ba58 pc=0xc46cda
```

(This is on a Windows 10 machine, but we have hundreds of other nodes running on Windows 7/8.1/10 without issue).

**Comment by tmm1** [comment]
I suspected hardware failure on this node, and sure enough "Windows Memory Diagnostic" surfaced a bad stick of RAM.
