### ISSUE TITLE
Scorch persister stuck after segment creation fails?

### ISSUE THREAD

**Issue by tmm1** [blevesearch/bleve#1305]
On low memory devices, we see frequent memory allocation errors when submitting indexing batches to scorch:

<pre>
2019/11/03 08:18:50 [DVR] Fetching guide data for 262 stations in USA-WI48449-X @ 2019-11-18 2:00PM
2019/11/03 08:19:02 [DVR]   indexed 1761 airings (247 channels) [1s fetch, 10s index]
2019/11/03 08:19:03 [DVR]   indexed 112 movies (35 channels) [0s fetch, 0s index]
2019/11/03 08:19:03 [DVR] Fetching guide data for 262 stations in USA-WI48449-X @ 2019-11-18 8:00PM
2019/11/03 08:19:07 [DVR] Error indexing airings: error opening new segment at USA-WI48449-X.airings/store/00000000668c.zap, cannot allocate memory
2019/11/03 08:19:08 [DVR] Fetching guide data for 262 stations in USA-WI48449-X @ 2019-11-19 2:00AM
2019/11/03 08:19:12 [DVR] Error indexing airings: cannot allocate memory
2019/11/03 08:19:26 [IDX] Pruned 3839 expired airings from USA-WI48449-X in 10.116005734s.
</pre>

Then, a few hours later we experience a full crash of the process. The stack shows that the persister is sitting inside pausePersisterForMergerCatchUp() and the Batch is still stuck in prepareSegment()

<pre>
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0xb68bd6 m=2 sigcode=4294967290

goroutine 0 [idle]:
runtime: unknown pc 0xb68bd6
stack: frame={sp:0x66c9a87c, fp:0x0} stack=[0x6649b034,0x66c9ac34)
66c9a7fc:  00b6bcf1  00000000  00000000  00000000 
66c9a80c:  00000000  00000000  00000000  00000000 
66c9a81c:  00000000  00000000  00000000  00000000 
66c9a82c:  00000000  00000000  00000000  00000000 
66c9a83c:  00000000  00000000  00000000  00000000 
66c9a84c:  00000000  00000000  00000000  00000000 
66c9a85c:  00000000  00000000  00000000  00000000 
66c9a86c:  01afd358  66c9b300  00000001  01afd358 
66c9a87c: <01afd358  00b6bc7b  01afd358  66c9b300 
66c9a88c:  00b6be9b  00000000  00000000  00000000 
66c9a89c:  00000000  66c9a8cd  010d770c  00000000 
66c9a8ac:  010cb153  66c90043  00b698ef  010cb120 
66c9a8bc:  00000005  4d5f434c  41535345  2f534547 
66c9a8cc:  6362696c  006f6d2e <github.com/blevesearch/bleve/index/scorch/segment/zap.mergeStoredAndRemap.func2+802>  00b6989d  00000000 
66c9a8dc:  00000000  00000043  00000000  00000000 
66c9a8ec:  00000000  00000000  00000000  00000000 
runtime: unknown pc 0xb68bd6
stack: frame={sp:0x66c9a87c, fp:0x0} stack=[0x6649b034,0x66c9ac34)
66c9a7fc:  00b6bcf1  00000000  00000000  00000000 
66c9a80c:  00000000  00000000  00000000  00000000 
66c9a81c:  00000000  00000000  00000000  00000000 
66c9a82c:  00000000  00000000  00000000  00000000 
66c9a83c:  00000000  00000000  00000000  00000000 
66c9a84c:  00000000  00000000  00000000  00000000 
66c9a85c:  00000000  00000000  00000000  00000000 
66c9a86c:  01afd358  66c9b300  00000001  01afd358 
66c9a87c: <01afd358  00b6bc7b  01afd358  66c9b300 
66c9a88c:  00b6be9b  00000000  00000000  00000000 
66c9a89c:  00000000  66c9a8cd  010d770c  00000000 
66c9a8ac:  010cb153  66c90043  00b698ef  010cb120 
66c9a8bc:  00000005  4d5f434c  41535345  2f534547 
66c9a8cc:  6362696c  006f6d2e <github.com/blevesearch/bleve/index/scorch/segment/zap.mergeStoredAndRemap.func2+802>  00b6989d  00000000 
66c9a8dc:  00000000  00000043  00000000  00000000 
66c9a8ec:  00000000  00000000  00000000  00000000 

goroutine 16 [chan receive, 519 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).prepareSegment(0x25c4a80, 0x1047268, 0x2bbe500, 0x336e000, 0xff, 0x100, 0x2620e40, 0x0, 0x0, 0x0)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/scorch.go:425 +0x3e4
github.com/blevesearch/bleve/index/scorch.(*Scorch).Batch(0x25c4a80, 0x30acac0, 0x0, 0x0)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/scorch.go:361 +0x6ec
github.com/blevesearch/bleve.(*indexImpl).Batch(0x28fcdc0, 0x2620e60, 0x0, 0x0)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index_impl.go:310 +0x94
github.com/fancybits/channels-server/dvr.(*Recorder).indexAirings(0x25ce8c0, 0x29e5490, 0xd, 0x30560a0, 0x309fd01, 0x0, 0x0, 0xd55233f0, 0xe, 0x1ae94c0, ...)

goroutine 50 [select, 2006 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).pausePersisterForMergerCatchUp(0x25c4a80, 0x1310, 0x0, 0x112a, 0x0, 0x0, 0x0, 0x0, 0x2ac21b0, 0x112a, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/persister.go:295 +0x2d0
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0x25c4a80)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/persister.go:117 +0x5f4
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/scorch.go:170 +0xc8

...

trap    0x6
error   0x0
oldmask 0x0
r0      0x0
r1      0x7fcd
r2      0x6
r3      0x7fcd
r4      0x6
r5      0x66c9b7c0
r6      0x2
r7      0x10c
r8      0x1
r9      0xe0
r10     0x2400540
fp      0x66c9a9bc
ip      0x10c
sp      0x66c9a87c
lr      0xb6bc7b
pc      0xb68bd6
cpsr    0x20000030
fault   0x0

</pre>

**Comment by tmm1** [comment]
On another instance a user is reporting 100% cpu usage and the stack shows levenshtein and roaring actively processing:

```

runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0xb5e726 m=2 sigcode=4294967290

goroutine 0 [idle]:
runtime: unknown pc 0xb5e726
stack: frame={sp:0x66d0d87c, fp:0x0} stack=[0x6650e034,0x66d0dc34)
66d0d7fc:  00b61841  00000000  00000000  00000000 
66d0d80c:  00000000  00000000  00000000  00000000 
66d0d81c:  00000000  00000000  00000000  00000000 
66d0d82c:  00000000  00000000  00000000  00000000 
66d0d83c:  00000000  00000000  00000000  00000000 
66d0d84c:  00000000  00000000  00000000  00000000 
66d0d85c:  00000000  00000000  00000000  00000000 
66d0d86c:  01ad95f8  66d0e300  00000001  01ad95f8 
66d0d87c: <01ad95f8  00b617cb  01ad95f8  66d0e300 
66d0d88c:  00b619eb  00000000  00000000  00000000 
66d0d89c:  00000000  66d0d8cd  010c7e70  00000000 
66d0d8ac:  010bb8b7  66d00043  00b5f43f  010bb884 
66d0d8bc:  00000005  4d5f434c  41535345  2f534547 
66d0d8cc:  6362696c  006f6d2e <github.com/couchbase/vellum/levenshtein.queryChars+130>  00b5f3ed  00000000 
66d0d8dc:  00000000  00000043  00000000  00000000 
66d0d8ec:  00000000  00000000  00000000  00000000 
runtime: unknown pc 0xb5e726
stack: frame={sp:0x66d0d87c, fp:0x0} stack=[0x6650e034,0x66d0dc34)
66d0d7fc:  00b61841  00000000  00000000  00000000 
66d0d80c:  00000000  00000000  00000000  00000000 
66d0d81c:  00000000  00000000  00000000  00000000 
66d0d82c:  00000000  00000000  00000000  00000000 
66d0d83c:  00000000  00000000  00000000  00000000 
66d0d84c:  00000000  00000000  00000000  00000000 
66d0d85c:  00000000  00000000  00000000  00000000 
66d0d86c:  01ad95f8  66d0e300  00000001  01ad95f8 
66d0d87c: <01ad95f8  00b617cb  01ad95f8  66d0e300 
66d0d88c:  00b619eb  00000000  00000000  00000000 
66d0d89c:  00000000  66d0d8cd  010c7e70  00000000 
66d0d8ac:  010bb8b7  66d00043  00b5f43f  010bb884 
66d0d8bc:  00000005  4d5f434c  41535345  2f534547 
66d0d8cc:  6362696c  006f6d2e <github.com/couchbase/vellum/levenshtein.queryChars+130>  00b5f3ed  00000000 
66d0d8dc:  00000000  00000043  00000000  00000000 
66d0d8ec:  00000000  00000000  00000000  00000000 


goroutine 32 [select, 610 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0x37e0000)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/introducer.go:61 +0x270
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/scorch.go:166 +0x68

goroutine 33 [select, 523 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).pausePersisterForMergerCatchUp(0x37e0000, 0x3f5, 0x0, 0x356, 0x0, 0x0, 0x0, 0x0, 0x3590f80, 0x356, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/persister.go:295 +0x2d0
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0x37e0000)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/persister.go:117 +0x5f4
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/scorch.go:170 +0xc8

goroutine 50 [runnable]:
github.com/RoaringBitmap/roaring.byteSliceAsUint16Slice(0x7ebde00e, 0x2, 0x2a7c7a, 0x2, 0x2a7c7a, 0x0)
	github.com/RoaringBitmap/roaring@v0.4.21/serialization_generic.go:87 +0xfc
github.com/RoaringBitmap/roaring.(*roaringArray).readFrom(0x3ad99c0, 0x10325f8, 0x31b6090, 0x6f37bc, 0x427aa40, 0x40, 0x6e4248)
	github.com/RoaringBitmap/roaring@v0.4.21/roaringarray.go:677 +0x52c
github.com/RoaringBitmap/roaring.(*Bitmap).FromBuffer(0x3ad99c0, 0x7ebddffe, 0x12, 0x2a7c8a, 0x0, 0x1, 0x56817c0, 0x408716c)
	github.com/RoaringBitmap/roaring@v0.4.21/roaring.go:106 +0x84
github.com/blevesearch/bleve/index/scorch/segment/zap.(*PostingsList).read(0x3ad9980, 0x371ff5, 0x0, 0x4312100, 0x394b91c, 0x394ba30)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/posting.go:307 +0x280
github.com/blevesearch/bleve/index/scorch/segment/zap.(*Dictionary).postingsListFromOffset(0x4312100, 0x371ff5, 0x0, 0x4a91c40, 0x3ad9980, 0x4404000, 0x202, 0x202)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/dict.go:72 +0x54
github.com/blevesearch/bleve/index/scorch/segment/zap.persistMergedRest(0x505f500, 0xa, 0xa, 0x505eff0, 0xa, 0xa, 0x3daa2a0, 0x1c, 0x1c, 0x3b31ae0, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/merge.go:315 +0xd70
github.com/blevesearch/bleve/index/scorch/segment/zap.MergeToWriter(0x505f500, 0xa, 0xa, 0x505eff0, 0xa, 0xa, 0x400, 0x3b31ac0, 0x37b2900, 0x66f39350, ..)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/merge.go:140 +0x238
github.com/blevesearch/bleve/index/scorch/segment/zap.MergeSegmentBases(0x505f500, 0xa, 0xa, 0x505eff0, 0xa, 0xa, 0x47b3470, 0x2c, 0x400, 0x37b2900, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/merge.go:81 +0x1b8
github.com/blevesearch/bleve/index/scorch/segment/zap.Merge(0x505e0c0, 0xa, 0xa, 0x505eff0, 0xa, 0xa, 0x47b3470, 0x2c, 0x400, 0x37b2900, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/merge.go:56 +0xe8
github.com/blevesearch/bleve/index/scorch.(*Scorch).planMergeAtSnapshot(0x37e0000, 0x4516780, 0x30e6c80, 0x4390, 0x1ac5760)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/merge.go:206 +0xc7c
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0x37e0000)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/merge.go:61 +0x3c4
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/scorch.go:172 +0xf8

goroutine 52 [select, 610 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0x3120000)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/introducer.go:61 +0x270
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/scorch.go:166 +0x68

goroutine 53 [select, 610 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0x3120000)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/persister.go:219 +0x8e8
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/scorch.go:170 +0xc8

goroutine 54 [select, 610 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0x3120000)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/merge.go:97 +0x324
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/scorch.go:172 +0xf8

```

**Comment by tmm1** [comment]
> error opening new segment at USA-WI48449-X.airings/store/00000000668c.zap, cannot allocate memory

It looks like the underlying error here is coming from the mmap call returning ENOMEM.

> runtime/cgo: pthread_create failed: Resource temporarily unavailable

Similarly here, pthread tries to call mmap to allocate a stack and that's still failing, causing pthread_create to return EAGAIN.

>http://rachid.koucha.free.fr/tech_corner/problem_of_thread_creation.html
>
> pthread_create() can fail with the ENOMEM errno (GLIBC v2.5) or EAGAIN (GLIBC 2.8) when the number of running threads is getting too big. This makes the cumulated memory space allocated to the embedding process (e.g. the stacks) too high and so, the mmap() system call fails.

According to the `mmap` [man page](http://man7.org/linux/man-pages/man2/mmap.2.html) there are three cases when this happens:

```
       ENOMEM No memory is available.

       ENOMEM The process's maximum number of mappings would have been
              exceeded.  This error can also occur for munmap(), when
              unmapping a region in the middle of an existing mapping, since
              this results in two smaller mappings on either side of the
              region being unmapped.

       ENOMEM (since Linux 4.7) The process's RLIMIT_DATA limit, described
              in getrlimit(2), would have been exceeded.
```

The maximum number of mappings is controlled by `vm.max_map_count`: https://www.systutorials.com/241561/maximum-number-of-mmaped-ranges-and-how-to-set-it-on-linux/

The [kernel docs for `max_map_count`](https://www.kernel.org/doc/Documentation/sysctl/vm.txt) state it is a per-process setting:

```
max_map_count:

This file contains the maximum number of memory map areas a process
may have. Memory map areas are used as a side-effect of calling
malloc, directly by mmap, mprotect, and madvise, and also when loading
shared libraries.

While most applications need less than a thousand maps, certain
programs, particularly malloc debuggers, may consume lots of them,
e.g., up to one or two maps per allocation.

The default value is 65536.
```

I verified that the systems having this issue have the default value set:

>$ cat /proc/sys/vm/max_map_count
>65530

Further, checking `/proc/self/maps` on my process shows less than 100 maps which is nowhere close to the 65k limit.

I also verified that `RLIMIT_DATA` is set to unlimited via `/proc/self/limits`. The kernel used on these instances is 3.10.105 so that shouldn't be enforced any way given the man page states ENOMEM is only returned starting with 4.7

I suppose this means that the system is actually running low on memory? I though mmap only needed to allocate virtual address space though, so I'm confused as to why mapping the zap file would return ENOMEM if the limits are all high.

There is also still some pathological behavior inside scorch when opening a zap segment fails, as the mergerLoop seems to go crazy and consume 100% cpu for hours afterwards.

**Comment by tmm1** [comment]
So far the crashes are all happening on armv7 processors. The first couple were from instances with only 512mb of ram, but I'm seeing another on an armv7 with 4GB RAM.

The crash always shows runnable goroutines working away at merging, even though its several hours after a batch failed and indexing was aborted.

```
goroutine 392 [runnable]:
github.com/blevesearch/bleve/index/scorch/segment/zap.(*chunkedIntCoder).Add(0x507d958, 0x75, 0x0, 0x507d648, 0x2, 0x2, 0x0, 0x48de800)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/intcoder.go:60 +0x310
github.com/blevesearch/bleve/index/scorch/segment/zap.mergeTermFreqNormLocs(0x4f693a0, 0x441b760, 0x10, 0x20, 0x4eee6c0, 0x44e6400, 0x104, 0x104, 0x507d8dc, 0x507d958, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/merge.go:473 +0x6f0
github.com/blevesearch/bleve/index/scorch/segment/zap.persistMergedRest(0x4f692a0, 0x6, 0x8, 0x4f692c0, 0x6, 0x8, 0x495ce00, 0x1b, 0x1b, 0x4f693a0, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/merge.go:329 +0xf80
github.com/blevesearch/bleve/index/scorch/segment/zap.MergeToWriter(0x4f692a0, 0x6, 0x8, 0x4f692c0, 0x6, 0x8, 0x400, 0x4f69380, 0x4620140, 0x603b0, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/merge.go:140 +0x238
github.com/blevesearch/bleve/index/scorch/segment/zap.MergeSegmentBases(0x4f692a0, 0x6, 0x8, 0x4f692c0, 0x6, 0x8, 0x544f6b0, 0x2c, 0x400, 0x4620140, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/merge.go:81 +0x1b8
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergeSegmentBases(0x3e12a80, 0x463cb40, 0x4f692a0, 0x6, 0x8, 0x4f692c0, 0x6, 0x8, 0x422cf80, 0x6, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/merge.go:313 +0x198
github.com/blevesearch/bleve/index/scorch.(*Scorch).persistSnapshotMaybeMerge(0x3e12a80, 0x463cb40, 0x0, 0x0, 0x0)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/persister.go:379 +0x358
github.com/blevesearch/bleve/index/scorch.(*Scorch).persistSnapshot(0x3e12a80, 0x463cb40, 0x43443e0, 0x3d02, 0x1af1700)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/persister.go:340 +0x9c
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0x3e12a80)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/persister.go:141 +0x6f8
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/scorch.go:170 +0xc8

goroutine 393 [runnable]:
github.com/couchbase/vellum.(*fstStateV1).at(0x4af6540, 0x5173bcde, 0x555, 0xf7c38, 0x8b, 0x0, 0x0)
	github.com/couchbase/vellum@v0.0.0-20190829182332-ef2e028c01fd/decoder_v1.go:106 +0x1f0
github.com/couchbase/vellum.(*decoderV1).stateAt(0x42425c0, 0x8b, 0x1047968, 0x4af6540, 0x69, 0x0, 0x1046388, 0x0)
	github.com/couchbase/vellum@v0.0.0-20190829182332-ef2e028c01fd/decoder_v1.go:65 +0x84
github.com/couchbase/vellum.(*FSTIterator).next(0x40c1260, 0xffffffff, 0x0, 0x0)
	github.com/couchbase/vellum@v0.0.0-20190829182332-ef2e028c01fd/fst_iterator.go:239 +0x198
github.com/couchbase/vellum.(*FSTIterator).Next(0x40c1260, 0x0, 0x3f800000)
	github.com/couchbase/vellum@v0.0.0-20190829182332-ef2e028c01fd/fst_iterator.go:185 +0x24
github.com/blevesearch/bleve/index/scorch/segment/zap.(*enumerator).Next(0x62fc380, 0x422d1c0, 0x10)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/enumerator.go:100 +0xac
github.com/blevesearch/bleve/index/scorch/segment/zap.persistMergedRest(0x5828ab0, 0xa, 0xa, 0x5828a80, 0xa, 0xa, 0x495cd20, 0x1c, 0x1c, 0x4ffe100, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/merge.go:340 +0xc1c
github.com/blevesearch/bleve/index/scorch/segment/zap.MergeToWriter(0x5828ab0, 0xa, 0xa, 0x5828a80, 0xa, 0xa, 0x400, 0x4ffe0e0, 0x4620140, 0x66e1e42b, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/merge.go:140 +0x238
github.com/blevesearch/bleve/index/scorch/segment/zap.MergeSegmentBases(0x5828ab0, 0xa, 0xa, 0x5828a80, 0xa, 0xa, 0x4fba6f0, 0x2c, 0x400, 0x4620140, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/merge.go:81 +0x1b8
github.com/blevesearch/bleve/index/scorch/segment/zap.Merge(0x5828a50, 0xa, 0xa, 0x5828a80, 0xa, 0xa, 0x4fba6f0, 0x2c, 0x400, 0x4620140, ...)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/segment/zap/merge.go:56 +0xe8
github.com/blevesearch/bleve/index/scorch.(*Scorch).planMergeAtSnapshot(0x3e12a80, 0x463cb40, 0x50a4400, 0x3d02, 0x1af1700)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/merge.go:206 +0xc7c
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0x3e12a80)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/merge.go:61 +0x3c4
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/scorch.go:172 +0xf8
```

**Comment by tmm1** [comment]
I added an "asyncErrorCallbackName" and now I see this error printed over and over:

> merging err: cannot allocate memory

@sreekanth-cb any ideas?

**Comment by tmm1** [comment]
It looks like the persister is writing the same data to new zap segments over and over:

<pre>

-rw------- 1 root root 104M Nov 13 21:18 0000000125a8.zap
-rw------- 1 root root 104M Nov 13 21:18 0000000125a9.zap
-rw------- 1 root root 104M Nov 13 21:18 0000000125aa.zap
-rw------- 1 root root 104M Nov 13 21:19 0000000125ab.zap
-rw------- 1 root root 104M Nov 13 21:19 0000000125ac.zap
-rw------- 1 root root 104M Nov 13 21:19 0000000125ad.zap
-rw------- 1 root root 104M Nov 13 21:20 0000000125ae.zap
-rw------- 1 root root 104M Nov 13 21:20 0000000125af.zap
</pre>

**Comment by mschoch** [comment]
I think we had identified some paths that have this exact behavior, some error happens that is essentially unrecoverable by scorch, and scorch will just retry it indefinitely.  I don't remember the details, but I think it was slightly less trivial to fix because some of the components are decoupled and it makes the problem harder to detect.

**Comment by tmm1** [comment]
Another variation that happens repeatedly:

<pre>
2019/11/14 11:37:46 got err persisting snapshot: error opening new segment at 00000000d7b1.zap, cannot allocate memory
2019/11/14 11:37:46 got err persisting snapshot: error opening new segment at 00000000d7b1.zap, cannot allocate memory
2019/11/14 11:37:47 got err persisting snapshot: error opening new segment at 00000000d7b1.zap, cannot allocate memory
2019/11/14 11:37:47 got err persisting snapshot: error opening new segment at 00000000d7b1.zap, cannot allocate memory
</pre>

**Comment by tmm1** [comment]
So the underlying issue here appears to be the limited address space available on 32-bit processes.

In leveldb, the number of active mmap is limited for this reason:

https://github.com/google/leveldb/blob/master/util/env_posix.cc#L45-L46

https://github.com/google/leveldb/blob/3ea9147c575dd8d509ed2596a4d67ec32405c6a1/util/env_posix.cc#L68-L72

**Comment by tmm1** [comment]
I was able to reproduce this behavior on an armv7l device myself with a large enough dataset. With the repro, I can now see `strace` showing the mmap call failing:

```
[pid 8919] 21:17:18.196313 openat(AT_FDCWD, "store/0000000125a6.zap", O_RDONLY|O_LARGEFILE|O_CLOEXEC <unfinished ...>
[pid 8919] 21:17:18.196392 <... openat resumed> ) = 17 <0.000048>
[pid 8919] 21:17:18.196897 mmap2(NULL, 108078675, PROT_READ, MAP_SHARED, 17, 0 <unfinished ...>
[pid 8919] 21:17:18.196976 <... mmap2 resumed> ) = -1 ENOMEM (Cannot allocate memory) <0.000046>
```

`lsof` shows a large number of zap segments are mmap'd into the process.

Looking at `/proc/self/status`, I see the virtual memory address space is suspiciously close to 2GB:

```
VmPeak: 2075724 kB
VmSize: 2074224 kB
```

It looks like on 32-bit linux kernels, you can pick if user-space gets 1G, 2G or 3G addressable space: http://thinkiii.blogspot.com/2014/02/arm32-linux-kernel-virtual-address-space.html

I confirmed that the kernel on these devices was compiled with `CONFIG_VMSPLIT_2G` instead of the default `CONFIG_VMSPLIT_3G`.

**Comment by tmm1** [comment]
> I think we had identified some paths that have this exact behavior, some error happens that is essentially unrecoverable by scorch, and scorch will just retry it indefinitely. I don't remember the details, but I think it was slightly less trivial to fix because some of the components are decoupled and it makes the problem harder to detect.

Yea it looks like that's what is happening here. This is particularly bad because one mmap failure starts a loop which both pegs the CPU at 100%, and also writes the same to new segments over and over filling up the entire disk.

**Comment by tmm1** [comment]
I opened #1308 and #1309 and verified they fix the pathological cpu/disk issues described above.

However, the underlying issue is still present and I could use some guidance on how to approach it. Clearly, assuming that all zap segments can be mmap'd into memory at the same time is not a viable design.

Can I perhaps close some old segments more eagerly, especially when switching to a new snapshot?

Longer term, it seems `zap.Segment` might need to learn how to map files into ram on-demand, and unmap when done (atleast on 32-bit platforms). That will require a bunch of refactoring for sure, but does it seem viable?

**Comment by mschoch** [comment]
I'm probably wrong, but here we go.  To me the whole appeal of using mmap is that we're not in the business of managing what to keep in ram vs disk.  If we accept that this abstraction is essentially broken, and we still have page things in and out ourselves, then we might as well ditch mmap at the same time.

Another option would be to just admit that the scorch design doesn't work well (and therefore we shouldn't support) 32-bit platforms.  This isn't to diminish the utility of having that, but to be honest about the fact that the design isn't well suited for it.

In my opinion, scorch now has a code complexity issue.  I personally find the goroutine model difficult to reason about.  And previous attempts to enhance scorch for things like in-memory merging, an in-memory only mode have been more difficult than anticipated (only in-memory merging has been completed).  My point is, I'm not sure there's a straightforward way to revisit the "everything is mmap'd" design in this code base.  That assumption is pretty fundamental, and changing it might mean an entirely new design.

**Comment by tmm1** [comment]
@mschoch Appreciate your perspective. I understand that mmap-usage is deeply ingrained, and the simplest path might be to document that scorch doesn't support 32-bit platforms.

Unfortunately for me, I've converted several thousand nodes over from leveldb and am now seeing this issue across a number of ARM instances. I would prefer not to switch back, but perhaps I have no choice. The idea of running different backends per architecture is also not appealing.

I'm hoping for a simple workaround, and am exploring some options:

1. It appears part of the issue is that the golang runtime itself reserves 800mb of the virtual address space: https://github.com/golang/go/issues/35677. Reducing that might help give me more breathing room.

2. Right now I'm storing my original document as a field in my mapping, which is increasing the size of the zap segments. I could move these to another database reducing the size of the segments and thus the mmap address space requirements.

3. My dataset is already pretty small, and does not grow over time. It easily fits within 1GB, so the problem I'm running into occurs only during segment merging: the memory requirements are doubled because both the old and new (merged) segments have to be mapped at the same time. An acceptable trade-off for me would be an option to unmap old segments before mapping in the new merged segment, although I can see how the goroutine model used makes this complicated to implement.

**Comment by tmm1** [comment]
> My point is, I'm not sure there's a straightforward way to revisit the "everything is mmap'd" design in this code base. That assumption is pretty fundamental, and changing it might mean an entirely new design.

I'm trying to scope this out further. It seems like the mmap access is fairly limited, and only happens from four files inside `index/scorch/segment/zap`. Would it not be possible to replace all the `s.mem[x:y]` accesses on i386 with a method like `s.readMem(x,y)` which read the requested bytes directly from the open file?

cc @steveyen

**Comment by tmm1** [comment]
A similar error loop can be triggered if someone deletes the index's `store/` directory from underneath the process:

>got err persisting snapshot: open store/00188425bfa.zap: no such file or directory

In this case, the loop is very tight and the error message is printed many hundreds of times per second. We have one node where the log file alone grew to 2TB with these error messages.
