### ISSUE TITLE
Crash when indexing ~80,000 documents using moss and scorch

### ISSUE THREAD

**Issue by wrouesnel** [blevesearch/bleve#1339]
I'm batching documents into batches of ~250 and progressively indexing them into a bleve index initialized with
```go
	ds.index, err = bleve.NewUsing(indexRoot, mapping, scorch.Name, moss.Name, nil)
```
Around the 34,000 document mark I get a go-routine panic with the following trace:
```
panic: runtime error: index out of range [-1]

goroutine 42 [running]:
github.com/blevesearch/bleve/index/scorch/segment/zap.mergeStoredAndRemap.func2(0xc02f49f6c0, 0x34, 0x62, 0xc05f385d90, 0x1, 0x2005e, 0x0, 0x0, 0x0, 0x1)
	/home/user/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/segment/zap/merge.go:689 +0x57d
github.com/blevesearch/bleve/index/scorch/segment/zap.(*SegmentBase).visitDocument(0xc03ebb0100, 0xc03b088960, 0x24f, 0xc04366b6b8, 0xbe, 0x0)
	/home/user/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/segment/zap/segment.go:384 +0x392
github.com/blevesearch/bleve/index/scorch/segment/zap.mergeStoredAndRemap(0xc03ed90300, 0x8, 0x8, 0xc03ed996c0, 0x8, 0x8, 0xc062845380, 0xc043b7e000, 0x14705, 0x14705, ...)
	/home/user/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/segment/zap/merge.go:687 +0x47f
github.com/blevesearch/bleve/index/scorch/segment/zap.MergeToWriter(0xc03ed90300, 0x8, 0x8, 0xc03ed996c0, 0x8, 0x8, 0x400, 0xc06282e030, 0xc00951e3c0, 0x20300f, ...)
	/home/user/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/segment/zap/merge.go:134 +0x1ef
github.com/blevesearch/bleve/index/scorch/segment/zap.MergeSegmentBases(0xc03ed90300, 0x8, 0x8, 0xc03ed996c0, 0x8, 0x8, 0xc0375f6000, 0x35, 0x400, 0xc00951e3c0, ...)
	/home/user/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/segment/zap/merge.go:81 +0x24c
github.com/blevesearch/bleve/index/scorch/segment/zap.Merge(0xc03ed9bac0, 0x8, 0x8, 0xc03ed996c0, 0x8, 0x8, 0xc0375f6000, 0x35, 0x400, 0xc00951e3c0, ...)
	/home/user/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/segment/zap/merge.go:56 +0x121
github.com/blevesearch/bleve/index/scorch.(*Scorch).planMergeAtSnapshot(0xc006866c00, 0xc0375e1200, 0xc009536000, 0x1, 0x0)
	/home/user/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/merge.go:206 +0x95d
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc006866c00)
	/home/user/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/merge.go:61 +0x247
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/home/user/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/scorch.go:172 +0x125
```
This seems to occur consistently with this dataset,

**Comment by mschoch** [comment]
First, there is some misunderstanding I would like to clear up.  You have specified "moss and scorch", but Moss is a key/value store, but the scorch indexing scheme does NOT use key/value stores for storage.  So, when using scorch, the key/value store specified is not used (thought it can't be the empty string for backwards compatibility reasons).  We recommend passing in the value `scorch.Name` for both.

As for the actual issue, it appears that possibly the merge is trying to work on a field that doesn't exist, this returns a fieldID of 0, which when we subtract 1 from it, gives us an invalid index.

It would seem to be something unique about your data or mapping, as we routinely index significantly more data and have never seen this issue.

Are you able to share your data/mapping?

**Comment by wrouesnel** [comment]
Running with a debugger attached I wasn't able to retrigger the error at around the same document mark, so it's possibly some sort race?

Looking at my document mapping I found two misnamed fields, though that was for disabling these fields from indexing (which meant a lot more data then I expected was being indexed - including a free `map[string]interface{}` field which held arbitrary JSON data).

So it seems like a missing field is possible, but since the automatic mapping would descend into the key/value store anyway I'm not sure how this could be avoided?

**Comment by mschoch** [comment]
It's unlikely to be a race, based on where the panic happens.  The merge is a very linear sequence of operations taking place on a single goroutine, and we only ever do a single merge at a time (within an index) because they are so resource intensive.

When I suggested a missing field, I didn't mean to imply anything wrong with your code or data.  To be 100% clear, a panic at this point strongly suggests a bug inside bleve.  Rather, what I meant was that perhaps some unique combination of data+mapping leads to a case that we do not handle correctly inside bleve.

The easiest way for us to help you get this issue fixed is to have a program that you can share which reproduces the behavior.  If you can share your data+mapping, it might be as simple as that if we can wire up a simple test harness around it.  If not, the next best thing is to try and isolate the problematic data.  You can take a binary search approach, and see if the same issue comes up with one half of the data or the other, and repeating that.  That might narrow things down enough that you can either identify the problem directly, or try to sanitize the data in a way that you can share it.

Let us know if any of these options will work.

**Comment by mschoch** [comment]
Maybe try adding some logging here:

https://github.com/blevesearch/bleve/blob/master/index/scorch/segment/zap/merge.go#L688

Print out the `docNum` and `field`.  The docNum is an internal identifier that won't immediately the document, but if you add more log statements higher up the stack we can identify the origin segment file.

The inputs to the merge should be on disk, so another option might be to share the index at the time of this crash.  From it we might be able to reconstruct the problem.

**Comment by EfChouTR** [comment]
@mschoch I can confirm we are having this same issue with our data being indexed. When we reach around 50K+ rows (batching 250 at a time into the indexer), we start getting a bunch too many files open errors. This pertains to the zap files during the indexing process. Maybe we are indexing too quickly and the go routine to consolidate and compress the data is lagging behind?

**Comment by mschoch** [comment]
@EfChouTR please open a separate issue.  If you get "too many open files", there are specific things we may ask to debug and possibly configure differently for your use case.  This issue should be limited to the panic described above.

I don't see evidence yet that these are the same issue.  Many uses of bleve/scorch will have lots of files, that doesn't mean all issues are the same.
