### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#144]
```
$ ./bleve-bench -config configs/leveldb.json -count 3000 -cpuprofile=cpu-leveldb3.profile
Using KV store: leveldb
Using KV config: map[string]interface {}{}
elapsed,docs,avg_single_doc_ms,avg_batched_doc_ms,query_water_matches,first_query_water_ms,avg_repeated5_query_water_ms
25406,1000,32.368264,24.284388,179,211.156938,43.627602
runtime: newstack called from g=0xc208090900
	m=0xc208020a80 m->curg=0xc208090b40 m->g0=0xc208090a20 m->gsignal=0xc208090900
runtime.onM(0xb0208d70)
	/Users/mschoch/Documents/research/go/go/src/runtime/asm_amd64.s:235 +0x2f
runtime.morestackc()
	/Users/mschoch/Documents/research/go/go/src/runtime/stack.c:885 +0x1e
runtime.sighandler(0x20600000001b, 0xb02091f0, 0xb0209258, 0xc208090a20)
	/Users/mschoch/Documents/research/go/go/src/runtime/signal_amd64x.c:44 +0x14
runtime.sigtramp(0x489e6c8, 0x2060778332b0, 0x1570000015700, 0x200003500000085, 0x8b2e91d, 0x0, 0xc20801200c, 0xb0209310, 0x0, 0xb0209328, ...)
	/Users/mschoch/Documents/research/go/go/src/runtime/sys_darwin_amd64.s:229 +0x69
fatal error: runtime: wrong goroutine in newstack

runtime stack:
runtime.throw(0x4709417)
	/Users/mschoch/Documents/research/go/go/src/runtime/panic.go:491 +0xad
runtime.newstack()
	/Users/mschoch/Documents/research/go/go/src/runtime/stack.c:710 +0x16b
runtime.morestack()
	/Users/mschoch/Documents/research/go/go/src/runtime/asm_amd64.s:324 +0x7e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/Users/mschoch/Documents/research/go/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20805dfe8 sp=0xc20805dfe0

goroutine 1 [runnable]:
encoding/binary.dataSize(0x4361880, 0xc209d5c940, 0xcd, 0x4361880)
	/Users/mschoch/Documents/research/go/go/src/encoding/binary/binary.go:348
encoding/binary.Read(0x4c12990, 0xc209d60e00, 0x4c129b8, 0x4737a40, 0x433e4a0, 0xc209d5c940, 0x0, 0x0)
	/Users/mschoch/Documents/research/go/go/src/encoding/binary/binary.go:208 +0x10fa
github.com/blevesearch/bleve/index/upside_down.(*TermFrequencyRow).parseV(0xc209d5c900, 0xc20993eef0, 0xc, 0xc, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/upside_down/row.go:316 +0x2b4
github.com/blevesearch/bleve/index/upside_down.NewTermFrequencyRowKV(0xc20993ef00, 0x9, 0x10, 0xc20993eef0, 0xc, 0xc, 0xc2090d1108, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/upside_down/row.go:359 +0xc0
github.com/blevesearch/bleve/index/upside_down.(*termSummaryIncr).Merge(0x4737a40, 0xc20993ef00, 0x9, 0x10, 0xc20993eef0, 0xc, 0xc, 0x0, 0x0, 0x0, ...)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/upside_down/row_merge.go:20 +0xaf
github.com/blevesearch/bleve/index/store.AssociativeMergeChain.Merge(0xc20a028e00, 0x2, 0x2, 0xc20993ef00, 0x9, 0x10, 0xc20993eef0, 0xc, 0xc, 0x0, ...)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/store/kvstore.go:62 +0x166
github.com/blevesearch/bleve/index/store/leveldb.(*Batch).Execute(0xc20dc644e0, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/store/leveldb/batch.go:82 +0x2c9
github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).batchRows(0xc208030960, 0x4c12548, 0xc209345978, 0xc20de26000, 0xe049, 0xec00, 0xc20a57e000, 0x64, 0x80, 0xc2090d15c0, ...)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:121 +0x60b
github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).Batch(0xc208030960, 0xc2080c0a10, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:597 +0xb95
github.com/blevesearch/bleve.(*indexImpl).Batch(0xc208010150, 0xc2080c0a00, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index_impl.go:319 +0x535
main.main()
	/Users/mschoch/go/src/github.com/blevesearch/bleve-bench/index.go:111 +0x1e61

goroutine 5 [chan receive]:
github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0xc20800a0c0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:40 +0x73
created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:32 +0x66

goroutine 6 [chan receive]:
github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0xc20800a0c0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:40 +0x73
created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:32 +0x66

goroutine 7 [chan receive]:
github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0xc20800a0c0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:40 +0x73
created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:32 +0x66

goroutine 8 [chan receive]:
github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0xc20800a0c0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:40 +0x73
created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:32 +0x66

goroutine 9 [syscall]:
runtime.CPUProfile(0x0, 0x0, 0x0)
	/Users/mschoch/Documents/research/go/go/src/runtime/cpuprof.go:424 +0x45
runtime/pprof.profileWriter(0x4c11cd0, 0xc20802e020)
	/Users/mschoch/Documents/research/go/go/src/runtime/pprof/pprof.go:594 +0x1f
created by runtime/pprof.StartCPUProfile
	/Users/mschoch/Documents/research/go/go/src/runtime/pprof/pprof.go:588 +0x14e

goroutine 50 [syscall, locked to thread]:
runtime.goexit()
	/Users/mschoch/Documents/research/go/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by mschoch** [comment]
Never saw this before today.  Observed it would happen at different points in time, but would always happen.  Rebuilt executable and problem has gone away again.

Googling suggests that it may be related to code which does crazy things with signal handling.  To my knowledge we're not doing that (and I don't think leveldb does that).

I rebuilt the executable and the problem seems to have gone away again.

**Comment by mschoch** [comment]
As pointed out by @steveyen this was observed with cpu profiling enabled.  Probably would have been helpful if I ran the problematic executable without that flag once...

**Comment by mschoch** [comment]
Closing this as I haven't seen it in almost a year.
