### ISSUE TITLE
Configurable bbolt flock timeouts?

### ISSUE THREAD

**Issue by tmm1** [blevesearch/bleve#1491]
Sometimes randomly, for reasons I am still not quite sure of, I will see a deadlock trying to open an index:

```
goroutine 1 [sleep]:
time.Sleep(0x2faf080)
	runtime/time.go:188 +0xc0
github.com/etcd-io/bbolt.flock(0x4000b12800, 0x1, 0x0, 0x180, 0x40000aa210)
	github.com/etcd-io/bbolt@v1.3.3/bolt_unix.go:40 +0x8c
github.com/etcd-io/bbolt.Open(0x4000b719e0, 0x1c, 0x180, 0x22951e0, 0xa, 0x4000b719e0, 0x1c)
	github.com/etcd-io/bbolt@v1.3.3/db.go:223 +0x170
github.com/blevesearch/bleve/index/scorch.(*Scorch).openBolt(0x4000171400, 0x400071b6b0, 0x4000171400)
	github.com/blevesearch/bleve@v0.8.2-0.20191030071327-189ee421f71e/index/scorch/scorch.go:205 +0x424
github.com/blevesearch/bleve/index/scorch.(*Scorch).Open(0x4000171400, 0x6, 0x4000630ae0)
	github.com/blevesearch/bleve@v0.8.2-0.20191030071327-189ee421f71e/index/scorch/scorch.go:160 +0x28
github.com/blevesearch/bleve.openIndexUsing(0x4000b717c0, 0x14, 0x400071b6b0, 0x40006f60e0, 0x0, 0x0)
	github.com/blevesearch/bleve@v0.8.2-0.20191030071327-189ee421f71e/index_impl.go:174 +0x468
github.com/blevesearch/bleve.OpenUsing(...)
	github.com/blevesearch/bleve@v0.8.2-0.20191030071327-189ee421f71e/index.go:294
```

bbolt provides a timeout argument to its `flock` method, but it is unused. Can we add a scorch option to be able to pass this through?

**Comment by meirwah** [comment]
I have seen it too:
```
#	0x44ed5c	time.Sleep+0x12c											/usr/local/go/src/runtime/time.go:105
#	0xef7689	github.com/etcd-io/bbolt.flock+0x99									/home/circleci/.go_workspace/pkg/mod/github.com/etcd-io/bbolt@v0.0.0-20190809044356-35b666109344/bolt_unix.go:40
#	0xefd5d5	github.com/etcd-io/bbolt.Open+0x1a5									/home/circleci/.go_workspace/pkg/mod/github.com/etcd-io/bbolt@v0.0.0-20190809044356-35b666109344/db.go:223
#	0xf22997	github.com/blevesearch/bleve/index/scorch.(*Scorch).openBolt+0x547					/home/circleci/.go_workspace/pkg/mod/github.com/blevesearch/bleve@v0.8.2-0.20200122202155-99c4fac3d098/index/scorch/scorch.go:205
#	0xf2232e	github.com/blevesearch/bleve/index/scorch.(*Scorch).Open+0x2e						/home/circleci/.go_workspace/pkg/mod/github.com/blevesearch/bleve@v0.8.2-0.20200122202155-99c4fac3d098/index/scorch/scorch.go:160
#	0xf87155	github.com/blevesearch/bleve.openIndexUsing+0x515							/home/circleci/.go_workspace/pkg/mod/github.com/blevesearch/bleve@v0.8.2-0.20200122202155-99c4fac3d098/index_impl.go:174
#	0x11362de	github.com/blevesearch/bleve.OpenUsing+0x29e	
```

@mschoch can we bump this ?

**Comment by mschoch** [comment]
@tmm1 @meirwah 

OK, I have pushed an alternate PR to address this.  It is very similar to the one @tmm1 put together, the difference is that I think it is cleaner to have the duration specified as a string (many places rely on the JSON serialization of this config, and as a raw integer the time.Duration without units has led to confusion in the past).

Please review: https://github.com/blevesearch/bleve/pull/1553
