### ISSUE TITLE
The index file is damaged, and data cannot be written or deleted.

### ISSUE THREAD

**Issue by lh15200218** [blevesearch/bleve#1591]
That's how I used it.
var index bleve.Index
var batch = index.NewBatch()
index.Batch(batch)

goroutine 8288 [semacquire, 184 minutes]:
sync.runtime_SemacquireMutex(0x40004ba2fc, 0x400942d600, 0x1)
	/opt/buildtools/go-1.16.2/src/runtime/sema.go:71 +0x40
sync.(*Mutex).lockSlow(0x40004ba2f8)
	/opt/buildtools/go-1.16.2/src/sync/mutex.go:138 +0xf4
sync.(*Mutex).Lock(...)
	/opt/buildtools/go-1.16.2/src/sync/mutex.go:81
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch(0x40004ba280, 0x4001178120, 0x40083bc088, 0x0)
	/myProject/mod/github.com/blevesearch/bleve@v1.0.10/index/upsidedown/upsidedown.go:838 +0x125c
github.com/blevesearch/bleve.(*indexImpl).Batch(0x400019e070, 0x40030e5050, 0x0, 0x0)
	/myProject/mod/github.com/blevesearch/bleve@v1.0.10/index_impl.go:309 +0x9c

**Comment by lh15200218** [comment]
After ppprof is added, it is found that udc.writeMutex.Lock() in the Batch method in upsidedown.go under github.com\blevesearch\bleve@v1.0.10\index\upsidedown is not released.

**Comment by mschoch** [comment]
Please provide a working example to illustrate this problem.

**Comment by lh15200218** [comment]
The problem I had was microservice OOM. This problem occurs in only one of our many sites. Finally, the deadlock in the bleve is deadlocked. I have more than 50,000 records inserted into the index file. The batch := index.NewBatch() and index.Batch(batch) methods are used. After index.Batch(batch), the following operations are not executed. The call stack printed after ppprof is added is caused by lock release.

**Comment by lh15200218** [comment]
The problem I had was microservice OOM. This problem occurs in only one of our many sites. Finally, the deadlock in the bleve is deadlocked. I have more than 50,000 records inserted into the index file. The batch := index.NewBatch() and index.Batch(batch) methods are used. After index.Batch(batch), the following operations are not executed. The call stack printed after pprof is added is caused by lock release.

**Comment by lh15200218** [comment]
If the index file is replaced in another environment, data cannot be added or deleted. So for sure the index file is corrupted.

**Comment by mschoch** [comment]
You have not provided sufficient information for us to be able to help.  What do you expect us to do?

**Comment by lh15200218** [comment]
What information do I need to give you?

**Comment by lh15200218** [comment]
func main(){
	go syncRecord()
}

func syncRecord(){
	for {
		go A()  // This command is executed every two hours to obtain devices in the unsynchronized state.
		go B()  // Create indexes for unsynchronized devices in batches every 5 minutes.
	}
} 

There is a data table that records the synchronization status.
1、After the device table data is changed, the device synchronization status in the data table is changed to unsynchronized.
2、Processes A and B continuously check the data tables in the synchronization state. If the data tables are not synchronized, they create indexes.

**Comment by lh15200218** [comment]
func main(){
      go syncRecord()
}

func syncRecord(){
    for {
       go A() // This command is executed every two hours to obtain devices in the unsynchronized state.
       go B() // Create indexes for unsynchronized devices in batches every 5 minutes.
    }
}

There is a data table that records the synchronization status.
1、After the device table data is changed, the device synchronization status in the data table is changed to unsynchronized.
2、Processes A and B continuously check the data tables in the synchronization state. If the data tables are not synchronized, they create indexes.
