### ISSUE TITLE
Intermittent Scorch Windows Panic

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#1600]
After merging the upgrade of roaring to v.0.7.1, I saw the unit tests fail once with the following.  Rerunning the tests worked...

```
 panic: close of closed channel

goroutine 81 [running]:
github.com/blevesearch/bleve/v2/index/scorch.(*closeChWrapper).close(0xc0002990a0)
	D:/a/bleve/bleve/index/scorch/merge.go:228 +0xa5
github.com/blevesearch/bleve/v2/index/scorch.(*closeChWrapper).listen(0xc0002990a0)
	D:/a/bleve/bleve/index/scorch/merge.go:235 +0x1e5
created by github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).planMergeAtSnapshot
	D:/a/bleve/bleve/index/scorch/merge.go:275 +0x4cd
FAIL	github.com/blevesearch/bleve/v2/test	0.544s
FAIL
Error: Process completed with exit code 1.
```

**Comment by mschoch** [comment]
This is now known to be a duplicate of https://github.com/blevesearch/bleve/issues/1609 (which has a fix in progress, so I'm closing this one).
