### ISSUE TITLE
Panic in ParseFromKeyValue

### ISSUE THREAD

**Issue by 0x34d** [blevesearch/bleve#1885]
### File `index/upsidedown/row_test.go`

```go
func TestParseFromKeyValue(t *testing.T) {

	ParseFromKeyValue([]byte("d"), []byte("0"))
}
```

### backtrace
```log
--- FAIL: TestParseFromKeyValue (0.00s)
panic: runtime error: slice bounds out of range [:3] with capacity 1 [recovered]
	panic: runtime error: slice bounds out of range [:3] with capacity 1

goroutine 42 [running]:
testing.tRunner.func1.2({0x92fe40, 0xc0002bc3d8})
	/usr/lib/golang/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/lib/golang/src/testing/testing.go:1529 +0x39f
panic({0x92fe40, 0xc0002bc3d8})
	/usr/lib/golang/src/runtime/panic.go:884 +0x213
github.com/blevesearch/bleve/v2/index/upsidedown.(*DictionaryRow).parseDictionaryK(...)
	/home/0x34d/project/bleve/index/upsidedown/row.go:338
github.com/blevesearch/bleve/v2/index/upsidedown.NewDictionaryRowK(...)
	/home/0x34d/project/bleve/index/upsidedown/row.go:330
github.com/blevesearch/bleve/v2/index/upsidedown.NewDictionaryRowKV({0xc0002814b8, 0x1, 0x1}, {0xc0002814b9, 0x1, 0x1})
	/home/0x34d/project/bleve/index/upsidedown/row.go:315 +0x306
github.com/blevesearch/bleve/v2/index/upsidedown.ParseFromKeyValue({0xc0002814b8, 0x1, 0x1}, {0xc0002814b9, 0x1, 0x1})
	/home/0x34d/project/bleve/index/upsidedown/row.go:60 +0x19e
github.com/blevesearch/bleve/v2/index/upsidedown.TestParseFromKeyValue(0xc0002ceb60?)
	/home/0x34d/project/bleve/index/upsidedown/row_test.go:400 +0x77
testing.tRunner(0xc0002ced00, 0x9670e0)
	/usr/lib/golang/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1629 +0x3ea
exit status 2
FAIL	github.com/blevesearch/bleve/v2/index/upsidedown	0.399s
```

**Comment by metonymic-smokey** [comment]
thanks for raising this @0x34d.
However, the team has decided to stop supporting upsidedown indexes, and we currently only support scorch indexes. So I don't believe we'll be actively maintaining upsidedown.
