### ISSUE TITLE
panic in dictionary row value() method

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#197]
```
panic: runtime error: index out of range





goroutine 16 [running]:


runtime.panic(0x905620, 0xe861bc)


        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5


encoding/binary.PutUvarint(0xc2081cc6b8, 0x8, 0x8, 0x2000000000000000, 0x8)


        /usr/local/go/src/pkg/encoding/binary/varint.go:48 +0x78


github.com/blevesearch/bleve/index/upside_down.(*DictionaryRow).Value(0xc208313c20, 0x0, 0x0, 0x0)


        /appl/src/github.com/blevesearch/bleve/index/upside_down/row.go:196 +0xee


github.com/blevesearch/bleve/index/upside_down.(*upsideDownMerge).FullMerge(0xec3de0, 0xc2081cc688, 0x8, 0x8, 0x0, 0x0, 0x0, 0xc2081b5460, 0x1, 0x1, ...)


        /appl/src/github.com/blevesearch/bleve/index/upside_down/row_merge.go:58 +0x253


github.com/blevesearch/bleve/index/store.(*EmulatedMerge).Execute(0xc20819d080, 0x7f9b389ccb58, 0xc2080dc620, 0x0, 0x0)


        /appl/src/github.com/blevesearch/bleve/index/store/merge.go:93 +0x24a


github.com/blevesearch/bleve/index/store.(*EmulatedBatch).Execute(0xc20810b8c0, 0x0, 0x0)


        /appl/src/github.com/blevesearch/bleve/index/store/batch.go:45 +0x5d


github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).batchRows(0xc2080183c0, 0x7f9b389ccb58, 0xc2080dc620, 0xc20806d000, 0x490, 0x500, 0xc208052800, 0xd, 0x10, 0xc20809ab08, ...)


        /appl/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:144 +0x588


github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).Batch(0xc2080183c0, 0xc2087490d0, 0x0, 0x0)


        /appl/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:663 +0xaf5


github.com/blevesearch/bleve.(*indexImpl).Batch(0xc2080280e0, 0xc208750080, 0x0, 0x0)


        /appl/src/github.com/blevesearch/bleve/index_impl.go:304 +0x10f


main.main()


        /appl/workers/import_data_index.go:644 +0x319b





goroutine 19 [finalizer wait]:


runtime.park(0x430af0, 0xebe258, 0xe8c649)


        /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89


runtime.parkunlock(0xebe258, 0xe8c649)


        /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b


runfinq()


        /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf


runtime.goexit()


        /usr/local/go/src/pkg/runtime/proc.c:1445





goroutine 17 [syscall]:


runtime.goexit()


        /usr/local/go/src/pkg/runtime/proc.c:1445





goroutine 20 [select]:


github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0xc208004420, 0xc208004480)


        /appl/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:54 +0x16eb


created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue


        /appl/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:46 +0xc3





goroutine 21 [select]:


github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0xc208004420, 0xc208004480)


        /appl/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:54 +0x16eb


created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue


        /appl/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:46 +0xc3





goroutine 22 [select]:


github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0xc208004420, 0xc208004480)


        /appl/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:54 +0x16eb


created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue


        /appl/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:46 +0xc3





goroutine 23 [select]:


github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0xc208004420, 0xc208004480)


        /appl/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:54 +0x16eb


created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue


        /appl/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:46 +0xc3


exit status 2
```

**Comment by mschoch** [comment]
Confirmed that if the dictionary count is > 72057594037927935 then you will get this panic.

HOWEVER, its unreasonable that the value should have gotten this large in normal operation anyway.
