### ISSUE TITLE
panic during index -- parseV()

### ISSUE THREAD

**Issue by otoolep** [blevesearch/bleve#199]
Hitting this during a "query string" search. I have copied just the first go-routine stack trace.

Let me know if you need more information. This is with the code available as of the time of this bug report.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x6d2066]

goroutine 124 [running]:
github.com/blevesearch/bleve/index/upside_down.(*TermFrequencyRow).parseV(0x0, 0x7fc1822fe2ee, 0xa, 0x7ffffd51, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/index/upside_down/row.go:405 +0x156
github.com/blevesearch/bleve/index/upside_down.NewTermFrequencyRowKV(0x7fc1822fe2d2, 0x1c, 0x7ffffd6d, 0x7fc1822fe2ee, 0xa, 0x7ffffd51, 0x7ffffd01, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/index/upside_down/row.go:460 +0xc0
github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouchTermFieldReader).Next(0xc2085fee80, 0x0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/index/upside_down/reader.go:71 +0x2f5
github.com/blevesearch/bleve/search/searchers.(*TermSearcher).Next(0xc208235db0, 0x10, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/search/searchers/search_term.go:56 +0x57
github.com/blevesearch/bleve/search/searchers.(*DisjunctionSearcher).Next(0xc2083383f0, 0x10, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/search/searchers/search_disjunction.go:136 +0x4df
github.com/blevesearch/bleve/search/searchers.(*DisjunctionSearcher).Next(0xc208338460, 0xc2083d7c50, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/search/searchers/search_disjunction.go:136 +0x4df
github.com/blevesearch/bleve/search/searchers.(*BooleanSearcher).advanceNextMust(0xc20820ce10, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/search/searchers/search_boolean.go:114 +0x1d3
github.com/blevesearch/bleve/search/searchers.(*BooleanSearcher).Next(0xc20820ce10, 0xc2082b8240, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/search/searchers/search_boolean.go:223 +0xb21
github.com/blevesearch/bleve/search/collectors.(*TopScoreCollector).Collect(0xc2085fe140, 0x7fc18577be18, 0xc20820ce10, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/search/collectors/collector_top_score.go:68 +0x15b
github.com/blevesearch/bleve.(*indexImpl).Search(0xc208184690, 0xc208235a90, 0x0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/index_impl.go:411 +0xa96
github.com/blevesearch/bleve.func·001()
	/home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/index_alias_impl.go:471 +0xa4
created by github.com/blevesearch/bleve.func·002
	/home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/index_alias_impl.go:477 +0x19b
```

**Comment by mschoch** [comment]
Can you check the git commit of the bleve repo?  The line number at the top of the stack corresponds with a declaration.  https://github.com/blevesearch/bleve/blob/master/index/upside_down/row.go#L405

**Comment by otoolep** [comment]
Weird. This panic is happening on CircleCI. It does "go get" within a new container each test run, so I assumed it pulls down the latest. 

I see what it is doing.

**Comment by otoolep** [comment]
Cleared the cache on Circle, this doesn't occur any longer.
