### ISSUE TITLE
boltdb deadlock in TestReaderIsolation

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#208]
First showed up in automated testing:

```
=== RUN TestReaderIsolation
fatal error: all goroutines are asleep - deadlock!
goroutine 1 [chan receive]:
testing.RunTests(0x61f708, 0x6ae9a0, 0x2, 0x2, 0x3f1fa720f4787601)
	/usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc2080380f0, 0x6bacc0)
	/usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
	github.com/blevesearch/bleve/index/store/boltdb/_test/_testmain.go:54 +0x1d5
goroutine 6 [semacquire]:
sync.(*RWMutex).Lock(0xc208040490)
	/usr/local/go/src/sync/rwmutex.go:87 +0xa4
github.com/boltdb/bolt.(*DB).mmap(0xc208040340, 0x8000, 0x0, 0x0)
	/home/travis/gopath/src/github.com/boltdb/bolt/db.go:210 +0x5e
github.com/boltdb/bolt.(*DB).allocate(0xc208040340, 0x1, 0xc208012230, 0x0, 0x0)
	/home/travis/gopath/src/github.com/boltdb/bolt/db.go:635 +0x155
github.com/boltdb/bolt.(*Tx).allocate(0xc208020340, 0x1, 0x7f3cb246a000, 0x0, 0x0)
	/home/travis/gopath/src/github.com/boltdb/bolt/tx.go:399 +0x48
github.com/boltdb/bolt.(*node).spill(0xc208012230, 0x0, 0x0)
	/home/travis/gopath/src/github.com/boltdb/bolt/node.go:363 +0x2d2
github.com/boltdb/bolt.(*Bucket).spill(0xc208020358, 0x0, 0x0)
	/home/travis/gopath/src/github.com/boltdb/bolt/bucket.go:536 +0x1c4
github.com/boltdb/bolt.(*Tx).Commit(0xc208020340, 0x0, 0x0)
	/home/travis/gopath/src/github.com/boltdb/bolt/tx.go:151 +0x1ee
github.com/blevesearch/bleve/index/store/boltdb.(*Writer).Close(0xc20800a360, 0x0, 0x0)
	/home/travis/gopath/src/github.com/blevesearch/bleve/index/store/boltdb/writer.go:37 +0x5b
github.com/blevesearch/bleve/index/store/boltdb.CommonTestReaderIsolation(0xc2080621b0, 0x7f3cb25fbf18, 0xc2080365c0)
	/home/travis/gopath/src/github.com/blevesearch/bleve/index/store/boltdb/store_test.go:205 +0xe03
github.com/blevesearch/bleve/index/store/boltdb.TestReaderIsolation(0xc2080621b0)
	/home/travis/gopath/src/github.com/blevesearch/bleve/index/store/boltdb/store_test.go:49 +0x264
testing.tRunner(0xc2080621b0, 0x6ae9b8)
	/usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b
FAIL	github.com/blevesearch/bleve/index/store/boltdb	0.435s
```

**Comment by mschoch** [comment]
According to git bisect, `a450f843ee57645db062a4fe472c4509a7a1c7a2 is the first bad commit`

**Comment by mschoch** [comment]
I've opened an issue with boltdb here: https://github.com/boltdb/bolt/issues/378

Its not clear to me yet if this is supported behavior or not.
