### ISSUE TITLE
index out of range - concurrent query/insert

### ISSUE THREAD

**Issue by rnzconde** [blevesearch/bleve#264]
Greetings,

I am seeing the following panic when using the index:

```
panic: runtime error: index out of range

goroutine 15 [running]:
github.com/blevesearch/bleve/index/upside_down.(*TermFrequencyRow).KeyTo(0xc208104c60, 0xc209551000, 0x1000, 0x1000, 0x1, 0x0, 0x0)
	/home/rn/work/git/devops-utils-temp/awsfind/build/go-get-libs/src/github.com/blevesearch/bleve/index/upside_down/row.go:396 +0x251
github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).mergeOldAndNew(0xc20804e000, 0x0, 0xc208181a00, 0x3e, 0x64, 0xc209489240, 0x2, 0x2, 0xc2086dfce8, 0x0, ...)
	/home/rn/work/git/devops-utils-temp/awsfind/build/go-get-libs/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:430 +0x4a4
github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).Update(0xc20804e000, 0xc208594e40, 0x0, 0x0)
	/home/rn/work/git/devops-utils-temp/awsfind/build/go-get-libs/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:398 +0x717
github.com/blevesearch/bleve.(*indexImpl).Index(0xc208011960, 0xc208c538c0, 0x11, 0x84baa0, 0xc208433b80, 0x0, 0x0)
	/home/rn/work/git/devops-utils-temp/awsfind/build/go-get-libs/src/github.com/blevesearch/bleve/index_impl.go:276 +0x39c
main.func·004()
```

This is happening while I am concurrently writing and reading from the index.

Thanks,

-Ryan

**Comment by mschoch** [comment]
It doesn't appear to be related to the concurrency, just a place where our new buffer-reuse code fails to check that the buffer is large enough.

**Comment by mschoch** [comment]
I have reproduced the problem in a test case.

**Comment by mschoch** [comment]
Thanks for reporting the problem, if you still see issues let me know.

**Comment by rnzconde** [comment]
Awesome. It is working properly now. Thanks for the quick fix!
