### ISSUE TITLE
panic in shingle token filter

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#387]
```
panic: interface conversion: interface {} is nil, not *analysis.Token

goroutine 32 [running]:
panic(0x6a93e0, 0xc8201b62c0)
	/Users/mschoch/Documents/research/gosrc/src/runtime/panic.go:464 +0x3e6
github.com/blevesearch/bleve/analysis/token_filters/shingle.(*ShingleFilter).shingleCurrentRingState(0xc820091a40, 0x0, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/analysis/token_filters/shingle/shingle.go:90 +0x761
github.com/blevesearch/bleve/analysis/token_filters/shingle.(*ShingleFilter).Filter(0xc820091a40, 0xc8201a4000, 0x83, 0x400, 0x0, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/analysis/token_filters/shingle/shingle.go:67 +0x5a5
github.com/blevesearch/bleve/analysis.(*Analyzer).Analyze(0xc820069080, 0xc820029000, 0x3f5, 0x400, 0x0, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/analysis/type.go:84 +0x26c
main.analyzerWorker(0xc820069080, 0xc82006a660, 0xeceed38d5, 0x1800e7b3, 0xb6d8e0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve-bench/cmd/bleve-analyzer/main.go:193 +0xd6
main.main.func1(0xc820069080, 0xc82006a660, 0xc8201641a0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve-bench/cmd/bleve-analyzer/main.go:102 +0x4d
created by main.main
	/Users/mschoch/go/src/github.com/blevesearch/bleve-bench/cmd/bleve-analyzer/main.go:104 +0x60d
panic: interface conversion: interface {} is nil, not *analysis.Token

goroutine 36 [running]:
panic(0x6a93e0, 0xc82012c180)
	/Users/mschoch/Documents/research/gosrc/src/runtime/panic.go:464 +0x3e6
github.com/blevesearch/bleve/analysis/token_filters/shingle.(*ShingleFilter).shingleCurrentRingState(0xc820091a40, 0x0, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/analysis/token_filters/shingle/shingle.go:90 +0x761
github.com/blevesearch/bleve/analysis/token_filters/shingle.(*ShingleFilter).Filter(0xc820091a40, 0xc8201ae000, 0x1, 0x400, 0x0, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/analysis/token_filters/shingle/shingle.go:67 +0x5a5
github.com/blevesearch/bleve/analysis.(*Analyzer).Analyze(0xc820069080, 0xc8201aa000, 0x5, 0x8, 0x0, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/analysis/type.go:84 +0x26c
main.analyzerWorker(0xc820069080, 0xc82006a660, 0xeceed38d5, 0x1800e7b3, 0xb6d8e0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve-bench/cmd/bleve-analyzer/main.go:193 +0xd6
main.main.func1(0xc820069080, 0xc82006a660, 0xc8201641a0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve-bench/cmd/bleve-analyzer/main.go:102 +0x4d
created by main.main
	/Users/mschoch/go/src/github.com/blevesearch/bleve-bench/cmd/bleve-analyzer/main.go:104 +0x60d
```

**Comment by mschoch** [comment]
Unsuccessfully attempted to reproduce this with go-fuzz.  Will need to go back to wikipedia dataset and see if its reproducible.
