### ISSUE TITLE
"slice bounds out of range error" on highlight multiple hits

### ISSUE THREAD

**Issue by tischda** [blevesearch/bleve#404]
Reproduce with:

```
package main

import (
	"fmt"
	"github.com/blevesearch/bleve"
)

func main() {
	// open a new index
	mapping := bleve.NewIndexMapping()
	index, err := bleve.New("example.bleve", mapping)
	if err != nil {
		fmt.Println(err)
		return
	}

	data1 := struct {
		Name string
	}{
		Name: "PCA PCA",
	}

	data2 := struct {
		Name string
	}{
		Name: "PCA",
	}

	// index some data
	index.Index("id1", data1)
	index.Index("id2", data2)

	// search for some text
	query := bleve.NewMatchQuery("pca")
	search := bleve.NewSearchRequest(query)
	search.Highlight = bleve.NewHighlight()
	searchResults, err := index.Search(search)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(searchResults)
}
```

Result:

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x8b3e80, 0xc08200a080)
        C:/usr/bin/go/src/runtime/panic.go:481 +0x3f4
github.com/blevesearch/bleve/search/highlight/fragmenters/simple.(*Fragmenter).Fragment(0xc0820c58f0, 0xc0820c594d, 0x3, 0x3, 0xc0820c1820, 0x3, 0x4, 0x0, 0x0, 0x0)
        c:/usr/src/golang/public/src/github.com/blevesearch/bleve/search/highlight/fragmenters/simple/fragmenter_simple.go:57 +0x881
github.com/blevesearch/bleve/search/highlight/highlighters/simple.(*Highlighter).BestFragmentsInField(0xc0820bd890, 0xc082009400, 0xc082009540, 0x953dc8, 0x4, 0x1, 0x0, 0x0, 0x0)
        c:/usr/src/golang/public/src/github.com/blevesearch/bleve/search/highlight/highlighters/simple/highlighter_simple.go:91 +0x537
github.com/blevesearch/bleve.(*indexImpl).SearchInContext(0xc08202e070, 0x205010, 0xc08200ade8, 0xc082009180, 0x0, 0x0, 0x0)
        c:/usr/src/golang/public/src/github.com/blevesearch/bleve/index_impl.go:509 +0x1f3d
github.com/blevesearch/bleve.(*indexImpl).Search(0xc08202e070, 0xc082009180, 0xc1de00, 0x0, 0x0)
        c:/usr/src/golang/public/src/github.com/blevesearch/bleve/index_impl.go:372 +0x86
main.main()
        c:/usr/src/golang/awl/src/github.com/tischda/testbleve/main.go:37 +0x46f
```

Expected:

```
2 matches, showing 1 through 2, took 0
    1. id2 (0.594535)
        Name
                <mark>PCA</mark>
    2. id1 (0.594535)
        Name
                <mark>PCA</mark> <mark>PCA</mark>
```

Works in v0.3.0

**Comment by mschoch** [comment]
Thanks for reporting this.  I think I ran into the same thing while working on the indexapiwork PR.  I have a fix on that branch but I didn't pull it over to master.  We've run into other issues and delayed that PR, so let me just pull over that one fix to master.

I'll update again shortly.

**Comment by mschoch** [comment]
I just moved that fix over to master.  Let me know if you continue to see problems.

**Comment by tischda** [comment]
This fixes my problem, thank you.
