### ISSUE TITLE
panic in collector_heap

### ISSUE THREAD

**Issue by dtylman** [blevesearch/bleve#416]
in `Results`, need to check that `size>=0`...

```go
func (hc *HeapCollector) Results() search.DocumentMatchCollection {
	count := hc.Len()
	size := count - hc.skip
	rv := make(search.DocumentMatchCollection, size)
```

```
panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range

goroutine 9 [running]:
panic(0x5003a0, 0xc4201b2000)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420090300)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x5003a0, 0xc4201b2000)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/blevesearch/bleve/search/collectors.(*HeapCollector).Results(0xc42042f880, 0xe154b8, 0xc420012518, 0x7f1ce0)
	/Users/danny/src/go/src/github.com/blevesearch/bleve/search/collectors/collector_heap.go:112 +0x58
github.com/blevesearch/bleve.(*indexImpl).SearchInContext(0xc420298930, 0xe154b8, 0xc420012518, 0xc42042f490, 0x0, 0x0, 0x0)
	/Users/danny/src/go/src/github.com/blevesearch/bleve/index_impl.go:443 +0x32a
github.com/blevesearch/bleve.(*indexImpl).Search(0xc420298930, 0xc42042f490, 0xe, 0x0, 0x0)
	/Users/danny/src/go/src/github.com/blevesearch/bleve/index_impl.go:372 +0x75
```

**Comment by mschoch** [comment]
What version of bleve is this?  There is no longer a HeapCollector type.

**Comment by dtylman** [comment]
weird. I thought i was working with the master. Will check again.

Anyhow - this will also happen on the master code:
```go
func (c *collectStoreHeap) Final(skip int, fixup collectorFixup) (search.DocumentMatchCollection, error) {
	count := c.Len()
	size := count - skip
	rv := make(search.DocumentMatchCollection, size)
```
