### ISSUE TITLE
Index interface  Batch()  runtime.throw(0xbd1a29, 0x2a)

### ISSUE THREAD

**Issue by foreverseven** [blevesearch/bleve#480]
goroutine 63 [running]:
runtime.throw(0xbd1a29, 0x2a)
	E:/tools/go-amd64/src/runtime/panic.go:566 +0x9c fp=0xc05ce8cc68 sp=0xc05ce8cc48
runtime.sigpanic()
	E:/tools/go-amd64/src/runtime/signal_windows.go:155 +0x19c fp=0xc05ce8cc98 sp=0xc05ce8cc68
runtime.additab(0x191dcf0, 0x1)
	E:/tools/go-amd64/src/runtime/iface.go:98 +0x93 fp=0xc05ce8cd88 sp=0xc05ce8cc98
runtime.getitab(0xb19640, 0x887bc0, 0x0, 0x1203858)
	E:/tools/go-amd64/src/runtime/iface.go:79 +0x1b6 fp=0xc05ce8ce20 sp=0xc05ce8cd88
Mon Oct 17 2016 15:05:28 GMT+0800 (中国标准时间):runtime.convI2I(0xb19640, 0x1053260, 0xc06a5b3620, 0x20, 0x12043a0)
	E:/tools/go-amd64/src/runtime/iface.go:316 +0x56 fp=0xc05ce8ce50 sp=0xc05ce8ce20
github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).mergeOldAndNew(0xc04e8c6380, 0x0, 0xc068615b00, 0x21, 0x21, 0xc06309f680, 0x20, 0x21, 0xc06309f8c0, 0x1, ...)
	E:/tools/gopath/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:542 +0xec1 fp=0xc05ce8d2b8 sp=0xc05ce8ce50
github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).Batch(0xc04e8c6380, 0xc05c5ce020, 0x0, 0x0)
	E:/tools/gopath/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:915 +0xc95 fp=0xc05ce8d780 sp=0xc05ce8d2b8
github.com/blevesearch/bleve.(*indexImpl).Batch(0xc04e99afc0, 0xc056bfc000, 0x0, 0x0)
	E:/tools/gopath/src/github.com/blevesearch/bleve/index_impl.go:319 +0xaa fp=0xc05ce8d7c8 sp=0xc05ce8d780
master/service.(*IndexService).IndexBatch(0x11e5100, 0xc056bfc000, 0x2, 0xc06a3c4958)

goroutine 111 [runnable]:
github.com/syndtr/goleveldb/leveldb/comparer.(*bytesComparer).Compare(0x1203858, 0xc05998ee03, 0x1a, 0x969e, 0xc06b6aecf0, 0x1c, 0x24, 0x1)
	<autogenerated>:1
github.com/syndtr/goleveldb/leveldb.(*iComparer).Compare(0xc04e8cc210, 0xc05998ee03, 0x22, 0x969e, 0xc06b6aecf0, 0x24, 0x24, 0x1)
	E:/tools/gopath/src/github.com/syndtr/goleveldb/leveldb/comparer.go:36 +0xee
github.com/syndtr/goleveldb/leveldb/table.(*block).seek.func1(0x1c4, 0xc04696d701)
	E:/tools/gopath/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:68 +0x1e5
Mon Oct 17 2016 15:05:28 GMT+0800 (中国标准时间):sort.Search(0x2d3, 0xc0423a1548, 0x447252)
	E:/tools/go-amd64/src/sort/search.go:66 +0x6d
github.com/syndtr/goleveldb/leveldb/table.(*block).seek(0xc0628dd200, 0x1050660, 0xc04e8cc210, 0x0, 0x2d3, 0xc06b6aecf0, 0x24, 0x24, 0xc0423a1610, 0xa226c1, ...)
	E:/tools/gopath/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:69 +0xb1
Mon Oct 17 2016 15:05:28 GMT+0800 (中国标准时间):github.com/syndtr/goleveldb/leveldb/table.(*blockIter).Seek(0xc0520470e0, 0xc06b6aecf0, 0x24, 0x24, 0x0)
	E:/tools/gopath/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:229 +0xac
github.com/syndtr/goleveldb/leveldb/table.(*Reader).find(0xc067d124e0, 0xc06b6aecf0, 0x24, 0x24, 0x432401, 0xc04e8cca90, 0x904900, 0x0, 0x0, 0x0, ...)
Mon Oct 17 2016 15:05:28 GMT+0800 (中国标准时间):, 0x24, 0x24, 0xc04e8cca90, 0x0, 0x0, 0x0, 0x0, ...)
	E:/tools/gopath/src/github.com/syndtr/goleveldb/leveldb/table.go:382 +0x1f8
github.com/syndtr/goleveldb/leveldb.(*version).get.func1(0x0, 0xc04da3aa50, 0xc06b6aecf0)
	E:/tools/gopath/src/github.com/syndtr/goleveldb/leveldb/version.go:167 +Mon Oct 17 2016 15:05:28 GMT+0800 (中国标准时间):	E:/tools/gopath/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:829 +0x261
github.com/syndtr/goleveldb/leveldb/table.(*Reader).Find(0xc067d124e0, 0xc06b6aecf0, 0x24, 0x24, 0x1, 0xc04e8cca90, 0x8e0729, 0x1203858, 0xc06b6aecf0, 0xa18c74, ...)
	E:/tools/gopath/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:888 +0x81
github.com/syndtr/goleveldb/leveldb.(*tOps).find(0xc04dcc68a0, 0xc04da3aa50, 0xc06b6aecf0Mon Oct 17 2016 15:05:28 GMT+0800 (中国标准时间):0x4f8
github.com/syndtr/goleveldb/leveldb.(*version).walkOverlapping(0xc06924ab90, 0x0, 0x0, 0x0, 0xc06b6aecf0, 0x24, 0x24, 0xc0423a1ab8, 0xc0423a1a88)
	E:/tools/gopath/src/github.com/syndtr/goleveldb/leveldb/version.go:111 +0x33b
github.com/syndtr/goleveldb/leveldb.(*version).get(0xc06924ab90, 0x0, 0x0, 0x0, 0xc06b6aecf0, 0x24, 0x24, 0xc04e8cca90, 0x0, 0x0, ...)
	E:/tools/gopath/src/github.com/syndtr/goleveldb/leveldb/version.go:221 +0x2b5
github.com/syndtr/goleveldb/leveldb.(*DB).get(0xc04e8c5080, 0x0, 0x0, 0x0, 0x0, 0xc056986000, 0x1c, 0x1000, 0x26c245, 0xc04e8cca90, ...)
	E:/tools/gopath/src/github.com/syndtr/goleveldb/leveldb/db.go:774Mon Oct 17 2016 15:05:28 GMT+0800 (中国标准时间): +0x2b6
github.com/syndtr/goleveldb/leveldb.(*Snapshot).Get(0xc06b3b1170, 0xc056986000, 0x1c, 0x1000, 0xc04e8cca90, 0x0, 0x0, 0x0, 0x0, 0x0)
	E:/tools/gopath/src/github.com/syndtr/goleveldb/leveldb/db_snapshot.go:113 +0x1a7
github.com/blevesearch/bleve/index/store/goleveldb.(*Reader).Get(0xc053720d50, 0xc056986000, 0x1c, 0x1000, 0x1000, 0x20, 0xb2f840, 0x0, 0x0)
Mon Oct 17 2016 15:05:28 GMT+0800 (中国标准时间):	E:/tools/gopath/src/github.com/blevesearch/bleve/index/store/goleveldb/reader.go:24 +0x73
github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).backIndexRowForDoc(0xc04e8c6380, 0x1051480, 0xc053720d50, 0xc047dc4460, 0x1b, 0x0, 0x0, 0x0)
	E:/tools/gopath/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:716 +0x1ed
github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).Batch.func2(0xc06a34a780, 0xc053720d20Mon Oct 17 2016 15:05:28 GMT+0800 (中国标准时间):, 0xc04e8c6380, 0xc053720d40, 0xc05c5ce020)
	E:/tools/gopath/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:845 +0x178
created by github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).Batch
	E:/tools/gopath/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:859 +0x384

why?

**Comment by mschoch** [comment]
Sorry to see that this results in a panic.  Unfortunately, this is the second report we've received recently of problems that appear to be related to consistency in goleveldb.  I'm not yet ready to assign blame, but just noting a pattern.

Could you please provide the following additional information?

Which git SHA of bleve are you using?
Which git SHA of goleveldb are you using?
What operations were you performing at the time you experienced the problem?  It appears that a batch index operation was in progress, was anything else happening concurrently?
