### ISSUE TITLE
Panic if requesting a page that does not exist

### ISSUE THREAD

**Issue by slavikm** [blevesearch/bleve#504]
`panic: runtime error: slice bounds out of range` in `/Users/slavik/go/src/github.com/demisto/server/vendor/github.com/blevesearch/bleve/search/collectors/slice.go:55` if you request a page that does not exist.

**Comment by slavikm** [comment]
Relevant trace for more details:

```
panic: runtime error: slice bounds out of range

goroutine 1068 [running]:
panic(0x1102320, 0xc420012100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/demisto/server/vendor/github.com/blevesearch/bleve/search/collectors.(*collectStoreSlice).Final(0xc420d77c60, 0x14, 0xc420646860, 0x33be0d, 0xecfc6ab7b, 0x78ecea5, 0x1f1f220, 0xecfc6ab7b)
	/Users/slavik/go/src/github.com/demisto/server/vendor/github.com/blevesearch/bleve/search/collectors/slice.go:55 +0xf1
github.com/demisto/server/vendor/github.com/blevesearch/bleve/search/collectors.(*TopNCollector).finalizeResults(0xc4206b06c0, 0x1cf5720, 0xc420d77cc0, 0x468f48, 0x0)
	/Users/slavik/go/src/github.com/demisto/server/vendor/github.com/blevesearch/bleve/search/collectors/topn.go:233 +0x85
github.com/demisto/server/vendor/github.com/blevesearch/bleve/search/collectors.(*TopNCollector).Collect(0xc4206b06c0, 0x2548028, 0xc420012430, 0x1cf1f80, 0xc4200a2630, 0x1cf5720, 0xc420d77cc0, 0x0, 0x0)
	/Users/slavik/go/src/github.com/demisto/server/vendor/github.com/blevesearch/bleve/search/collectors/topn.go:132 +0x2a4
github.com/demisto/server/vendor/github.com/blevesearch/bleve.(*indexImpl).SearchInContext(0xc4201e2850, 0x2548028, 0xc420012430, 0xc4206042a0, 0x0, 0x0, 0x0)
	/Users/slavik/go/src/github.com/demisto/server/vendor/github.com/blevesearch/bleve/index_impl.go:450 +0x306
github.com/demisto/server/vendor/github.com/blevesearch/bleve.(*indexImpl).Search(0xc4201e2850, 0xc4206042a0, 0xc42081b870, 0x1, 0x1)
	/Users/slavik/go/src/github.com/demisto/server/vendor/github.com/blevesearch/bleve/index_impl.go:384 +0x75
```

**Comment by slavikm** [comment]
Never mind, I think it was fixed in master.
