### ISSUE TITLE
SEGV during concurrent bleve index usage (android-arm64 + levigo)

### ISSUE THREAD

**Issue by tmm1** [blevesearch/bleve#634]
I have a server app that uses bleve with levigo and runs on a variety of platforms and all sorts of different hardware. I recently ported it to android/arm64 and have noticed a SEGV that only happens on that platform.

I'm using golang 1.9 w/ a slightly older build of bleve:

blevesearch/bleve@72731336bfbdca295267ea96703224259246ba5b
tmm1/blevex@58782622cfc67561b97cb8eee1f85bd973175e78

I'm not sure if this is a bug in my app, bleve, levigo, leveldb, or in golang itself. Here's the crash report with the most interesting goroutines listed. I would appreciate any thoughts or hypothesis.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4000017698 pc=0x20285915f8]

runtime stack:
runtime.throw(0x2028bda477, 0x2a)
	go/src/runtime/panic.go:605 +0x70
runtime.sigpanic()
	go/src/runtime/signal_unix.go:351 +0x264
runtime.inheap(...)
	go/src/runtime/mheap.go:377
runtime.gcmarkwb_m(0x442052bf20, 0x4425da67f0)
	go/src/runtime/mbarrier.go:163 +0xa0
runtime.writebarrierptr_prewrite1.func1()
	go/src/runtime/mbarrier.go:193 +0x54
runtime.systemstack(0x4420524f38)
	go/src/runtime/asm_arm64.s:241 +0x8c
runtime.mstart()
	go/src/runtime/proc.go:1125

goroutine 10734 [running]:
runtime.systemstack_switch()
	go/src/runtime/asm_arm64.s:190 +0x8 fp=0x442074b9f0 sp=0x442074b9e0 pc=0x20285d2d10
runtime.writebarrierptr_prewrite1(0x442052bf20, 0x4425da67f0)
	go/src/runtime/mbarrier.go:188 +0x8c fp=0x442074ba30 sp=0x442074b9f0 pc=0x20285916e4
runtime.writebarrierptr(0x442052bf20, 0x4425da67f0)
	go/src/runtime/mbarrier.go:216 +0x44 fp=0x442074ba60 sp=0x442074ba30 pc=0x202859175c
github.com/blevesearch/bleve/index/upsidedown.(*BackIndexTermEntry).Unmarshal(0x442052bf20, 0x44252786b3, 0x6, 0x105, 0x0, 0x0)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/upsidedown.pb.go:142 +0x1b0 fp=0x442074bb40 sp=0x442074ba60 pc=0x2028a91c28
github.com/blevesearch/bleve/index/upsidedown.(*BackIndexRowValue).Unmarshal(0x4420077630, 0x4425277c00, 0xbb8, 0xbb8, 0x4420077630, 0x202897fe01)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/upsidedown.pb.go:324 +0x198 fp=0x442074bc50 sp=0x442074bb40 pc=0x2028a92960
github.com/golang/protobuf/proto.UnmarshalMerge(0x4425277c00, 0xbb8, 0xbb8, 0x2029467760, 0x4420077630, 0x4420077630, 0x4420010050)
	app/.go/src/github.com/golang/protobuf/proto/decode.go:312 +0xf0 fp=0x442074bca0 sp=0x442074bc50 pc=0x202897ff68
github.com/golang/protobuf/proto.Unmarshal(0x4425277c00, 0xbb8, 0xbb8, 0x2029467760, 0x4420077630, 0x2029460b20, 0x4420010050)
	app/.go/src/github.com/golang/protobuf/proto/decode.go:300 +0x54 fp=0x442074bce0 sp=0x442074bca0 pc=0x202897fe4c
github.com/blevesearch/bleve/index/upsidedown.NewBackIndexRowKV(0x44277ba000, 0x12, 0x1000, 0x4425277c00, 0xbb8, 0xbb8, 0xbb8, 0x0, 0x0)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/row.go:735 +0x178 fp=0x442074bdd0 sp=0x442074bce0 pc=0x2028a88a80
github.com/blevesearch/bleve/index/upsidedown.backIndexRowForDoc(0x202946bfe0, 0x4420614000, 0x442074bee0, 0x11, 0x20, 0x0, 0x0, 0x0)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:1059 +0x174 fp=0x442074be90 sp=0x442074bdd0 pc=0x2028a9155c
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch.func2(0x4423546c60, 0x4424a3b970, 0x44206a6200, 0x4424a3b980, 0x4424a3b960)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:834 +0x194 fp=0x442074bfb0 sp=0x442074be90 pc=0x2028a9586c
runtime.goexit()
	go/src/runtime/asm_arm64.s:931 +0x4 fp=0x442074bfb0 sp=0x442074bfb0 pc=0x20285d503c
created by github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:822 +0x204


goroutine 157 [GC assist wait]:
github.com/blevesearch/bleve/index/upsidedown.NewTermFrequencyRow(...)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/row.go:486
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).deleteSingle(0x44206a6200, 0x44253c3d00, 0x11, 0x4420535b80, 0x0, 0x0, 0x0, 0x4420b13000, 0xe6, 0x100)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:711 +0x11c
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch(0x44206a6200, 0x4424a3b960, 0x44200fe198, 0x44207dcbc0)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:898 +0xc90
github.com/blevesearch/bleve.(*indexImpl).Batch(0x44200fe150, 0x44290d9f60, 0x0, 0x0)
	app/.go/src/github.com/blevesearch/bleve/index_impl.go:286 +0x88
_/app/dvr.(*Recorder).PruneAiringsWithQuery(0x442067e000, 0x20294709e0, 0x44200fe150, 0x20294611a0, 0x4420b1d700, 0x2028aeab4c)
	app/dvr/search.go:775 +0x190
_/app/dvr.(*Recorder).PruneAiringsForLineup(0x442067e000, 0x442024a400, 0xc)
	app/dvr/search.go:754 +0x194
_/app/dvr.(*Recorder).RunIndexer(0x442067e000)
	app/dvr/recorder.go:195 +0x28c
created by _/app/dvr.(*Recorder).Run
	app/dvr/recorder.go:150 +0x34

goroutine 158 [runnable, locked to thread]:
github.com/jmhodges/levigo._Cfunc_leveldb_readoptions_destroy(0x202a8191f0)
	github.com/jmhodges/levigo/_obj/_cgo_gotypes.go:785 +0x38
github.com/jmhodges/levigo.(*ReadOptions).Close.func1(0x202a8191f0)
	app/.go/src/github.com/jmhodges/levigo/options.go:177 +0x44
github.com/jmhodges/levigo.(*ReadOptions).Close(0x4420686620)
	app/.go/src/github.com/jmhodges/levigo/options.go:177 +0x24
github.com/tmm1/blevex/leveldb.(*Reader).Close(0x44205b4a00, 0x4424c8b7e0, 0x4420525200)
	app/.go/src/github.com/tmm1/blevex/leveldb/reader.go:54 +0x24
github.com/blevesearch/bleve/index/upsidedown.(*IndexReader).Close(0x44205b4a20, 0x4420525228, 0x44254d2948)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/index_reader.go:167 +0x2c
github.com/blevesearch/bleve.(*indexImpl).GetInternal.func1(0x202946fbc0, 0x44205b4a20, 0x44254d29f0)
	app/.go/src/github.com/blevesearch/bleve/index_impl.go:663 +0x28
github.com/blevesearch/bleve.(*indexImpl).GetInternal(0x4420102fc0, 0x4424c8b7e0, 0x11, 0x20, 0x4420b98000, 0x649, 0x649, 0x0, 0x0)
	app/.go/src/github.com/blevesearch/bleve/index_impl.go:672 +0x15c
_/app/dvr.searchResultToAirings(0x4420534a50, 0x4429a772c0, 0x2, 0x2, 0x2, 0x2, 0x0)
	app/dvr/search.go:584 +0x13c
_/app/dvr.(*Recorder).SearchAiringsWithQueryOnIndices(0x442067e000, 0x2029460f20, 0x4421ecb300, 0x4429a772c0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	app/dvr/search.go:530 +0x88
_/app/dvr.(*Recorder).SearchAiringsWithQuery(0x442067e000, 0x2029460f20, 0x4421ecb300, 0x20294f9f70, 0x0, 0x0)
	app/dvr/search.go:494 +0x60
_/app/dvr.(*Rule).SearchMatchingAirings(0x44290d6aa0, 0x442067e000, 0x20294f9f70, 0x44254d3788, 0x0)
	app/dvr/rule.go:271 +0x34
_/app/dvr.(*Rule).FindAirings(0x44290d6aa0, 0x0, 0x44254d35f8, 0x44254d3788)
	app/dvr/rule.go:264 +0x28
_/app/dvr.(*Recorder).RunScheduler(0x442067e000)
	app/dvr/recorder.go:614 +0x244
created by _/app/dvr.(*Recorder).Run
	app/dvr/recorder.go:151 +0x54
```

**Comment by tmm1** [comment]
Hm, I just had it happen again and this time there weren't even two goroutines operating on the index. Starting to suspect this might be a golang runtime bug specific to arm64..

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4000006578 pc=0x203b7dd330]

runtime stack:
runtime.throw(0x203be25477, 0x2a)
	go/src/runtime/panic.go:605 +0x70
runtime.sigpanic()
	go/src/runtime/signal_unix.go:351 +0x264
runtime.heapBitsForObject(0x442195e660, 0x442195b770, 0x0, 0x441ff361cb, 0x4400000000, 0x204da725f0, 0x442001d260, 0x68)
	go/src/runtime/mbitmap.go:392 +0x88
runtime.scanobject(0x442195b770, 0x442001d260)
	go/src/runtime/mgcmark.go:1187 +0x218
runtime.gcDrain(0x442001d260, 0xd)
	go/src/runtime/mgcmark.go:943 +0x1dc
runtime.gcBgMarkWorker.func2()
	go/src/runtime/mgc.go:1796 +0x16c
runtime.systemstack(0x442001e600)
	go/src/runtime/asm_arm64.s:241 +0x8c
runtime.mstart()
	go/src/runtime/proc.go:1125

goroutine 18 [GC worker (idle)]:
runtime.systemstack_switch()
	go/src/runtime/asm_arm64.s:190 +0x8 fp=0x442002b740 sp=0x442002b730 pc=0x203b81dd10
runtime.gcBgMarkWorker(0x442001c000)
	go/src/runtime/mgc.go:1760 +0x1ac fp=0x442002b7d0 sp=0x442002b740 pc=0x203b7e3e84
runtime.goexit()
	go/src/runtime/asm_arm64.s:931 +0x4 fp=0x442002b7d0 sp=0x442002b7d0 pc=0x203b82003c
created by runtime.gcBgMarkStartWorkers
	go/src/runtime/mgc.go:1655 +0x74

goroutine 57 [runnable]:
github.com/blevesearch/bleve/index/upsidedown.(*TermFrequencyRow).Key(0x4427e6ca78, 0x442770b1c8, 0x8, 0x4426c02860)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/row.go:390 +0x1b4
github.com/blevesearch/bleve/index/upsidedown.(*BackIndexRow).AllTermKeys(0x4424f17680, 0x0, 0xe2, 0x4426bfc000)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/row.go:648 +0x140
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).mergeOldAndNew(0x442010a400, 0x4424f17680, 0x442535a000, 0xe2, 0xe2, 0x4426bed000, 0x15, 0xf2, 0x4426bf4000, 0xdd, ...)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:515 +0x1c4
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch(0x442010a400, 0x442054c030, 0x4420102b38, 0x203c6bb040)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:904 +0x8b4
github.com/blevesearch/bleve.(*indexImpl).Batch(0x4420102af0, 0x442064d480, 0x0, 0x0)
	app/.go/src/github.com/blevesearch/bleve/index_impl.go:286 +0x88
_/app/dvr.(*Recorder).indexAirings(0x44201ec1a0, 0x44205a4050, 0xd, 0x4428aac090, 0x0, 0xed16ebb50, 0x442005b3e0, 0x13a52453c000, 0x0, 0xed16d6d54)
	app/dvr/recorder.go:403 +0xa20
_/app/dvr.(*Recorder).RunIndexer(0x44201ec1a0)
	app/dvr/recorder.go:277 +0xb80
created by _/app/dvr.(*Recorder).Run
	app/dvr/recorder.go:150 +0x34
```

**Comment by tmm1** [comment]
An older crash from a few months ago I dug up, using golang 1.8

```
unexpected fault address 0x400004bea8
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x400004bea8 pc=0x200cfc127c]

goroutine 5 [running]:
runtime.throw(0x200d4f970a, 0x5)
	go/src/runtime/panic.go:596 +0x70 fp=0x44207ad530 sp=0x44207ad510
runtime.sigpanic()
	go/src/runtime/signal_unix.go:297 +0x224 fp=0x44207ad580 sp=0x44207ad530
runtime.bulkBarrierPreWrite(0x4432faaea8, 0x4432f44a28, 0x10)
	go/src/runtime/mbitmap.go:581 +0x324 fp=0x44207ad610 sp=0x44207ad590
runtime.typedmemmove(0x200d6650c0, 0x4432faaea8, 0x4432f44a28)
	go/src/runtime/mbarrier.go:237 +0xa4 fp=0x44207ad640 sp=0x44207ad610
runtime.evacuate(0x200d6aeac0, 0x4426172570, 0x2)
	go/src/runtime/hashmap.go:1072 +0x5b4 fp=0x44207ad730 sp=0x44207ad640
runtime.growWork(0x200d6aeac0, 0x4426172570, 0x1)
	go/src/runtime/hashmap.go:957 +0x8c fp=0x44207ad750 sp=0x44207ad730
runtime.mapassign(0x200d6aeac0, 0x4426172570, 0x44207ad8a0, 0x200dc5b5d8)
	go/src/runtime/hashmap.go:513 +0x524 fp=0x44207ad7f0 sp=0x44207ad750
github.com/blevesearch/bleve/analysis.TokenFrequencies.MergeAll(0x4426172570, 0x200d613323, 0xd, 0x4432f96630)
	app/.go/src/github.com/blevesearch/bleve/analysis/freq.go:57 +0x2dc fp=0x44207ad910 sp=0x44207ad7f0
github.com/blevesearch/bleve/document.(*CompositeField).Compose(0x44261149c0, 0x200d613323, 0xd, 0x10, 0x4432f96630)
	app/.go/src/github.com/blevesearch/bleve/document/field_composite.go:97 +0xd8 fp=0x44207ad960 sp=0x44207ad910
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Analyze(0x44204be480, 0x442232c230, 0x44207adf38)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/analysis.go:77 +0x990 fp=0x44207adf00 sp=0x44207ad960
github.com/blevesearch/bleve/index.AnalysisWorker(0x442005f140, 0x442005f1a0)
	app/.go/src/github.com/blevesearch/bleve/index/analysis.go:79 +0xa4 fp=0x44207adfc0 sp=0x44207adf00
runtime.goexit()
	go/src/runtime/asm_arm64.s:981 +0x4 fp=0x44207adfc0 sp=0x44207adfc0
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
	app/.go/src/github.com/blevesearch/bleve/index/analysis.go:67 +0xc8

goroutine 58 [runnable]:
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch(0x44204be480, 0x442376df60, 0x0, 0x0)
	app/.go/src/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:854 +0x2b0
github.com/blevesearch/bleve.(*indexImpl).Batch(0x44200530a0, 0x442313ecc0, 0x0, 0x0)
	app/.go/src/github.com/blevesearch/bleve/index_impl.go:286 +0x94
_/app/dvr.(*Recorder).indexAirings(0x44200d8780, 0x44204169c0, 0xd, 0x442021ec60, 0xed0cd4298, 0x4400000000, 0x442005fbc0, 0x13a52453c000, 0x0, 0x0)
	app/dvr/recorder.go:399 +0xa4c
_/app/dvr.(*Recorder).RunIndexer(0x44200d8780)
	app/dvr/recorder.go:273 +0xb48
created by _/app/dvr.(*Recorder).Run
	app/dvr/recorder.go:146 +0x34
```
