### ISSUE TITLE
panic: runtime error: index out of range in go-porterstemmer.step5a()

### ISSUE THREAD

**Issue by armhold** [blevesearch/bleve#647]
Hi, I'm getting the following panic.

I initially ran into this with bleve v0.5.0, but I'm still getting the same error with latest master (6eea5b78). 

I'm new to bleve, so it's possible I'm doing something dumb. None of my code appears in the stack trace, but it happens when at/near the end of batch indexing about 360,000 documents. (I'm attempting to see if it also happens when not batched, but it takes a few hours to run... I will report back).

If the attached trace isn't enough to pinpoint this, kindly let me know how I can help you diagnose this.

Thank you.

go version go1.9.2 darwin/amd64

```
panic: runtime error: index out of range        

goroutine 7 [running]:
github.com/user/project/vendor/github.com/blevesearch/go-porterstemmer.step5a(0xc42938c540, 0x1, 0x3, 0xc42938c540, 0x1, 0x3)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/go-porterstemmer/porterstemmer.go:792 +0x10f
github.com/user/project/vendor/github.com/blevesearch/go-porterstemmer.StemWithoutLowerCasing(0xc42938c540, 0x3, 0x3, 0xc42938c540, 0x3, 0x3)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/go-porterstemmer/porterstemmer.go:896 +0x138
github.com/user/project/vendor/github.com/blevesearch/bleve/analysis/token_filters/porter.(*PorterStemmer).Filter(0x1a3bf68, 0xc4267b04b0, 0xa, 0xa, 0xc4267b04b0, 0xa, 0xa)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/analysis/token_filters/porter/porter.go:35 +0x9b
github.com/user/project/vendor/github.com/blevesearch/bleve/analysis.(*Analyzer).Analyze(0xc42005cfc0, 0xc42e2f3090, 0x45, 0x50, 0x540000c42e13ef01, 0x19ff6b0, 0x543bad5e7ecd7f3e)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/analysis/type.go:84 +0x120
github.com/user/project/vendor/github.com/blevesearch/bleve/document.(*TextField).Analyze(0xc425ecdc20, 0x5, 0xc4215eb8b6)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/document/field_text.go:51 +0x84
github.com/user/project/vendor/github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).Analyze.func1(0x18dbc40, 0xc425ecdc20, 0xc4215ebb01)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/index/upside_down/analysis.go:43 +0x399
github.com/user/project/vendor/github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).Analyze(0xc42012e480, 0xc425cb8cd0, 0xc4215ebf38)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/index/upside_down/analysis.go:65 +0x4d6
github.com/user/project/vendor/github.com/blevesearch/bleve/index.AnalysisWorker(0xc42001c240, 0xc42001c2a0)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/index/analysis.go:74 +0x55
created by github.com/user/project/vendor/github.com/blevesearch/bleve/index.NewAnalysisQueue
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/index/analysis.go:62 +0xcd
exit status 2
```

**Comment by mschoch** [comment]
Can you check the git SHA of the 'github.com/blevesearch/go-porterstemmer' repo?  The line number in the stack trace doesn't seem to match the latest in the repo:

https://github.com/blevesearch/go-porterstemmer/blob/master/porterstemmer.go#L792

Also, is it possible to troubleshoot the problem and figure out what term is being stemmed when it crashes?

**Comment by armhold** [comment]
Ah, I'm sorry, I think I might have posted the original stack trace from when I was still on v0.5.0.

Here- I just re-ran it with the following relevant portions from my Gopkg.lock:
```
[[projects]]
  name = "github.com/blevesearch/bleve"
  packages = [".","analysis","analysis/analyzer/keyword","analysis/analyzer/standard","analysis/datetime/flexible","analysis/datetime/optional","analysis/lang/en","analysis/token/lowercase","analysis/token/porter","analysis/token/stop","analysis/tokenizer/single","analysis/tokenizer/unicode","document","geo","index","index/store","index/store/boltdb","index/store/gtreap","index/upsidedown","mapping","numeric","registry","search","search/collector","search/facet","search/highlight","search/highlight/format/html","search/highlight/fragmenter/simple","search/highlight/highlighter/html","search/highlight/highlighter/simple","search/query","search/scorer","search/searcher"]
  revision = "6eea5b78da004393b1d06b8c88d1bed9ca0a94b2"

[[projects]]
  name = "github.com/blevesearch/go-porterstemmer"
  packages = ["."]
  revision = "b4dd94e38f29620fe0f97ae4b0f6994b0d5d75f0"
  version = "v1.0.1"

[[projects]]
  branch = "master"
  name = "github.com/blevesearch/segment"
  packages = ["."]
  revision = "762005e7a34fd909a84586299f1dd457371d36ee"

[[projects]]
  name = "github.com/boltdb/bolt"
  packages = ["."]
  revision = "2f1ce7a837dcb8da3ec595b1dac9d0632f0f99e8"
  version = "v1.3.1"
```

And the stack trace for this configuration is:

```
panic: runtime error: index out of range

goroutine 5 [running]:
github.com/user/project/vendor/github.com/blevesearch/go-porterstemmer.step5a(0xc44836f000, 0x1, 0x3, 0xc44836f000, 0x1, 0x3)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/go-porterstemmer/porterstemmer.go:792 +0x10f
github.com/user/project/vendor/github.com/blevesearch/go-porterstemmer.StemWithoutLowerCasing(0xc44836f000, 0x3, 0x3, 0xc44836f000, 0x3, 0x3)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/go-porterstemmer/porterstemmer.go:896 +0x138
github.com/user/project/vendor/github.com/blevesearch/bleve/analysis/token/porter.(*PorterStemmer).Filter(0x1a60738, 0xc43477d950, 0xa, 0xa, 0xc43477d950, 0xa, 0xa)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/analysis/token/porter/porter.go:40 +0x9b
github.com/user/project/vendor/github.com/blevesearch/bleve/analysis.(*Analyzer).Analyze(0xc42005cec0, 0xc42c3fde50, 0x45, 0x45, 0x45, 0x45, 0x64462f59158ea252)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/analysis/type.go:89 +0x120
github.com/user/project/vendor/github.com/blevesearch/bleve/document.(*TextField).Analyze(0xc4520b0ea0, 0x7, 0xc44a33b8b6)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/document/field_text.go:56 +0x84
github.com/user/project/vendor/github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Analyze.func1(0x1933b20, 0xc4520b0ea0, 0xc44a33bb01)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/index/upsidedown/analysis.go:48 +0x399
github.com/user/project/vendor/github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Analyze(0xc4201a6500, 0xc437895380, 0xc44a33bf38)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/index/upsidedown/analysis.go:70 +0x4d6
github.com/user/project/vendor/github.com/blevesearch/bleve/index.AnalysisWorker(0xc42001c240, 0xc42001c2a0)
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/index/analysis.go:79 +0x55
created by github.com/user/project/vendor/github.com/blevesearch/bleve/index.NewAnalysisQueue
	/Users/user/work/go/src/github.com/user/project/vendor/github.com/blevesearch/bleve/index/analysis.go:67 +0xcd
exit status 2
```

In this crash I also changed my code to not perform batching, so that doesn't seem to be the problem.  Thanks so much for your kind attention.

**Comment by mschoch** [comment]
I just checked the commit history of go-porterstemmer and I see this commit:

https://github.com/blevesearch/go-porterstemmer/commit/510f3fedde328d7e356a835bcf845630cf815e33

Which fixes issues identified in this same function.  And this commit is newer than the one you reported in your manifest.  Please update your go-porterstemmer to the latest commit, 23a2c8e5cf1f380f27722c6d2ae8896431dc7d0e

**Comment by armhold** [comment]
OK, I see what's going on. Even though I have pinned the latest revisions for bleve & go-porterstemmer in my Gopkg.toml, "dep" is ignoring my specified revision for go-porterstemmer, and instead using
the tagged release v1.0.1.

Checking the [dep documentation](https://github.com/golang/dep/blob/master/docs/FAQ.md#why-is-dep-ignoring-a-version-constraint-in-the-manifest) more carefully, it seems that dep is ignoring my constraint because I do not directly import the go-porterstemmer package in my code, so it's considered a transitive dependency, and my contraint is therefore ignored.

This is not terribly intuitive, but the fix is to simply do the following in my main.go:
```
import _ "github.com/blevesearch/go-porterstemmer"
```
So @mschoch, I'm sorry for wasting your time with a bug that you fixed long ago.

If I understand the dep contraint rules correctly, dep transitive dependencies will ignore master in favor of the latest semver tag, even if that tag is years out of date.  So if you tag a new release for go-porterstemmer, perhaps this will prevent others from hitting this snag.

I am happy to report that my indexer now completes successfully (and about 20x faster- nice upgrade!)
