### ISSUE TITLE
scorch crashes on writeDicts

### ISSUE THREAD

**Issue by xeizmendi** [blevesearch/bleve#895]
Scorch crashes if you have a mapping where the same term is included in both a field where we don't include the term vectors and another field where we do.

When that happens the frequency of the term is 2 but the locs array only contains one item inside the writeDicts function when processing  the term `something`.

Here is the example code and the output when running it (in macOS High Sierra):

```
package main

import (
	"log"

	"github.com/blevesearch/bleve"
	"github.com/blevesearch/bleve/analysis/analyzer/keyword"
	"github.com/blevesearch/bleve/analysis/analyzer/standard"
	"github.com/blevesearch/bleve/index/scorch"
)

func main() {
	mp := bleve.NewIndexMapping()
	keywordMapping := bleve.NewTextFieldMapping()
	keywordMapping.Analyzer = keyword.Name
	keywordMapping.Store = false
	keywordMapping.IncludeTermVectors = false
	textMapping := bleve.NewTextFieldMapping()
	textMapping.Analyzer = standard.Name
	textMapping.Store = false
	docMapping := bleve.NewDocumentStaticMapping()
	docMapping.AddFieldMappingsAt("keyword", keywordMapping)
	docMapping.AddFieldMappingsAt("text", textMapping)
	mp.AddDocumentMapping("doc", docMapping)
	mp.DefaultType = "doc"
	mp.DefaultMapping = docMapping
	mp.DefaultAnalyzer = standard.Name
	mp.DocValuesDynamic = false
	mp.StoreDynamic = false
	mp.IndexDynamic = false

	idx, err := bleve.NewUsing("idx_data", mp, scorch.Name, scorch.Name, nil)
	if err != nil {
		log.Fatalln(err)
	}

	data := map[string]string{
		"keyword": "something",
		"text":    "A sentence that includes something within.",
	}

	idx.Index("id", data)
}
```

```
panic: runtime error: index out of range

goroutine 1 [running]:
test/crashtest/vendor/github.com/blevesearch/bleve/index/scorch/segment/zap.(*interim).writeDicts(0xc4200c4a00, 0x6, 0x0, 0x0, 0x4, 0x4, 0xc420077b48)
	/Users/me/go/src/test/crashtest/vendor/github.com/blevesearch/bleve/index/scorch/segment/zap/new.go:643 +0x1b48
test/crashtest/vendor/github.com/blevesearch/bleve/index/scorch/segment/zap.(*interim).convert(0xc4200c4a00, 0xc42010b300, 0xc4200c4a00, 0xc, 0xc4201aea17, 0x3, 0x8, 0x0, 0xc420082000)
	/Users/me/go/src/test/crashtest/vendor/github.com/blevesearch/bleve/index/scorch/segment/zap/new.go:247 +0x386
test/crashtest/vendor/github.com/blevesearch/bleve/index/scorch/segment/zap.AnalysisResultsToSegmentBase(0xc42000e390, 0x1, 0x1, 0x400, 0x1, 0x1, 0x0)
	/Users/me/go/src/test/crashtest/vendor/github.com/blevesearch/bleve/index/scorch/segment/zap/new.go:53 +0x127
test/crashtest/vendor/github.com/blevesearch/bleve/index/scorch.(*Scorch).Batch(0xc4200aaa80, 0xc4201ec060, 0x0, 0x0)
	/Users/me/go/src/test/crastest/vendor/github.com/blevesearch/bleve/index/scorch/scorch.go:312 +0x7b2
test/crashtest/vendor/github.com/blevesearch/bleve/index/scorch.(*Scorch).Update(0xc4200aaa80, 0xc4200328c0, 0x13bf480, 0xc4201ae9c0)
	/Users/me/go/src/test/crashtest/vendor/github.com/blevesearch/bleve/index/scorch/scorch.go:246 +0xd9
test/crashtest/vendor/github.com/blevesearch/bleve.(*indexImpl).Index(0xc42018e150, 0x1441d90, 0x2, 0x13bf480, 0xc4201ae9c0, 0x0, 0x0)
	/Users/me/go/src/test/crashtest/crashtest/github.com/blevesearch/bleve/index_impl.go:257 +0x228
main.main()
	/Users/me/go/src/test/crashtest/crash.go:42 +0x470
```

The workaround is to include the term vectors for all the fields.
This panic only happens when using scorch, I have tried both moss and boltdb and it works without a problem.

**Comment by steveyen** [comment]
hi -- just to leave a status update/note on this, looks like there's a wrong assumption in scorch w.r.t. the term frequency and # of locations, and some of the necessary info to handle this case correctly is missing from the current scorch file format.  That is, it's likely a more involved fix than my first guess, and likely needs a file format bump.

Also, btw, @xeizmendi's test case was super valuable to jump quickly to the underlying problem.
