### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by oa98105** [blevesearch/bleve#951]
Hi,
In my code I have following lines
  
query := bleve.NewQueryStringQuery("my test string")
index, _ := bleve.Open(idx) // here idx is path to a folder which contains index_meta.json and store 
searchRequest := bleve.NewSearchRequest(query) 
searchResult, err := index.Search(searchRequest)

I get the following error when I reach at line searchResult, err := index.Search(searchRequest)
kindly guide error is as follows

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x77179e]

goroutine 1 [running]:
github.com/blevesearch/bleve.(*indexImpl).SearchInContext(0x0, 0xa58660, 0xc4200140e8, 0xc420176150, 0x0, 0x0, 0x0)
	/home/oa/go/src/github.com/blevesearch/bleve/index_impl.go:436 +0x5e
github.com/blevesearch/bleve.(*indexImpl).Search(0x0, 0xc420176150, 0xa5d380, 0x0, 0xa549a0)
	/home/oa/go/src/github.com/blevesearch/bleve/index_impl.go:368 +0x4d
main.querytitle(0x8682d0, 0x1d, 0x8613e8, 0x9)

**Comment by mschoch** [comment]
Most likely the index returned by Open() was nil, and there was an error returned.  Please check the error and log it so we can see why it failed.

**Comment by mschoch** [comment]
Which key/value store implementation are you using?  Typically having Open() hang at this point is caused by multiple processes trying to open the same index.  Only the first will succeed, the rest will all block until it is closed.

**Comment by oa98105** [comment]
Could you further elaborate "key/value store implementation" ?
i do following
for k, v := range map-containing-structures-from-input-json-as-in-msg-earlier {
			index.Index(strings.ToLower(k), v)
}
I notice that the code works the following way 
index-of-type-Index := indextitles(path-to-input-json, path-to-dir-index.belve)
querysearch(index-of-type-Index, query-string)

However following hangs
indextitles(path-to-input-json, path-to-dir-index.belve)
querysearch(path-to-dir-index.belve, query-string) where in this function it hangs at index, err := bleve.Open("path-to-dir-index.belve")

**Comment by mschoch** [comment]
Sorry, what I'm referring to is that the default implementation of bleve index allows you to change the underlying key/value store implemenation.  By default, we use BoltDB, which has the limitation I described.  Only one process can open the index at a time, all others will block at the exact point you described.

If you haven't configured a different key/value store, then you are using BoltDB.  Can check if any other processes are accessing the index at the same time?

**Comment by oa98105** [comment]
I haven't changed default settings so I am using BoltDB then. Do you know how to check if anyother process is accessing it. At least I am not running anyother program using boltDB. What do you suggest change to different db and where I may change the setting in your code? Or you suggest something else?

**Comment by mschoch** [comment]
No, I don't recommend changing because of this.  I'm just trying to identify some facts to pin down the cause of the problem you're observing.  Rather than speculate further, can you provide a full goroutine dump at the point the process hangs?

In linux you can do this by pressing CTRL+\

Then copy/paste the output from that into something like a github gist, and paste the link here.

**Comment by oa98105** [comment]
While preparing the code for you I noticed that I am calling index, err := bleve.Open("path-to-dir-index.belve") in a loop. And the reason initially was the multiple index files. Now I moved to only one index file and removed the loop it works. So I was just wondering if I want to use loop with multiple small index files should call index.close() at the end of iteration? My data is really large with millions of objects.
I also noticed in the result when my query is "my test title" do you this score is correct in the first case. Shouldn't it be 1. What is the similarity method you are using ? Thanks
 1. my test title (0.452513)
	title
		my test title
	year
		1991
    2. my test title is this (0.452513)
	title
		my test title is this
	year
		1991

**Comment by oa98105** [comment]
continuing to my message above I noticed that indexing is really really slow. With i7 single thread indexing a json file of size 1.6GB with 100000 entries is taking more than an hr and did not finished. Do you recommend me to use different store in case you have looked at this issue. 
Config.DefaultKVStore = "" this is the line in config.go I believe where I change to different store.
Thanks

**Comment by mschoch** [comment]
Yes, if you have large dataset you should move away from BoltDB as the indexing will continue to get slower.  I would suggest using the GoLevelDB option.

Also, you should index your documents in Batches, if you aren't already.

Finally, yes you should call Close when you're done indexing and querying.  This will free resources related to that index.

**Comment by oa98105** [comment]
Thanks. Yes I started indexing a file (1.6GB) in the night and it is still not finished after 8 hrs. Let me try it with GoLevelDB and Batches. 
Thanks!

**Comment by oa98105** [comment]
I am getting an error "unknown storage type" when creating index. In Package config I can also see

// kv stores
	_ "github.com/blevesearch/bleve/index/store/boltdb"
	_ "github.com/blevesearch/bleve/index/store/goleveldb"
	_ "github.com/blevesearch/bleve/index/store/gtreap"
	_ "github.com/blevesearch/bleve/index/store/moss"

my code
kvstore := "goleveldb"
	kvconfig := map[string]interface{}{
		"create_if_missing": true,
		//		"write_buffer_size":         536870912,
		//		"lru_cache_capacity":        536870912,
		//		"bloom_filter_bits_per_key": 10,
	}

	index, err = bleve.NewUsing(pathtoindexfiles, mapping, upsidedown.Name, kvstore, kvconfig)

	if err != nil {
		fmt.Println(err)
		log.Fatalln("Trouble making index!")
		panic(err)
	}
	defer index.Close()

**Comment by mschoch** [comment]
Generally, you should pass `goleveldb.Name` as the key/value store name, to ensure that the `github.com/blevesearch/bleve/index/store/goleveldb` package gets imported.

**Comment by oa98105** [comment]
Thanks. Today I tried without batch. Two major issues are: Very very long time and Very large size of index. I have tens of documents and each one has got millions of json records as shown in the gist here
https://gist.github.com/oa98105/2f3d9bc2cd53b0c1871f57545f16c50c
I am trying to make the search possible over title, authors and keywords. I tried a file of 1.6GB without batch it took 3 hrs with 3 GB of index size and not finished. With this size of index file if I have 100 files of size 1.6GB each I am not sure where it will go and how index impacts loading time. In the same gist I have shown the code as well. I was trying to find documentation for using batch but was not able to find to see how it works. Could you please suggest where should I define a new batch? Also do you have any suggestion to reduce the size. Or anyother suggestion in case you think bleve is not suitable for my task?
Thanks

**Comment by steveyen** [comment]
Hi @oa98105 -- apologies for another "try yet another thing" replies... the latest indexer engine for bleve that we've been working on is "scorch" (as a higher-performance alternative to the "upsidedown" index type)...

https://github.com/blevesearch/bleve/blob/master/index/scorch/scorch.go#L37

Wondering if you might give that a try and see if that works better for you?
