### ISSUE TITLE
Performance regression reported with d4c0a3e

### ISSUE THREAD

**Issue by abhinavdangeti** [blevesearch/bleve#997]
A performance regression has been reported by @aviadl . The degradation is between these 2 commits:
6108a7e...d4c0a3e

**Comment by abhinavdangeti** [comment]
Also provided by @aviadl, the test appears to get stuck on this goroutine:

```
github.com/blevesearch/bleve/index/scorch.(*Scorch).prepareSegment(0xc00093ea80, 0x6056220, 0xc000b70c80, 0xc0001df560, 0x1, 0x1, 0xc000326960, 0x0, 0x0)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:419 +0x427
github.com/blevesearch/bleve/index/scorch.(*Scorch).Batch(0xc00093ea80, 0xc0001df550, 0x0, 0x0)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:356 +0x758
github.com/blevesearch/bleve/index/scorch.(*Scorch).Update(0xc00093ea80, 0xc000975280, 0x5c1ae40, 0xc001106fc0)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:275 +0xd0
github.com/blevesearch/bleve.(*indexImpl).Index(0xc0002e20e0, 0xc000b60750, 0xb, 0x5c1ae40, 0xc001106fc0, 0x0, 0x0)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index_impl.go:257 +0x21e
```

Other goroutines:
```

goroutine 20 [chan receive, 1 minutes]:
github.com/demisto/server/vendor/github.com/alecthomas/log4go.(*ConsoleLogWriter).run(0xc0003b16a0, 0x60347c0, 0xc0000ce008)
	/Users/aviad/demisto/go/src/github.com/demisto/server/vendor/github.com/alecthomas/log4go/termlog.go:33 +0x10c
created by github.com/demisto/server/vendor/github.com/alecthomas/log4go.NewConsoleLogWriter
	/Users/aviad/demisto/go/src/github.com/demisto/server/vendor/github.com/alecthomas/log4go/termlog.go:26 +0xba

goroutine 8 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc0000ac180, 0xc0000ac1e0)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/analysis.go:102 +0x102
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/analysis.go:94 +0xc8

goroutine 9 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc0000ac180, 0xc0000ac1e0)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/analysis.go:102 +0x102
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/analysis.go:94 +0xc8

goroutine 10 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc0000ac180, 0xc0000ac1e0)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/analysis.go:102 +0x102
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/analysis.go:94 +0xc8

goroutine 11 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc0000ac180, 0xc0000ac1e0)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/analysis.go:102 +0x102
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/analysis.go:94 +0xc8


goroutine 51 [select]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc0007c8380)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 23 [chan receive]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).prepareSegment(0xc00093ea80, 0x6056220, 0xc000b70c80, 0xc0001df560, 0x1, 0x1, 0xc000326960, 0x0, 0x0)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:419 +0x427
github.com/blevesearch/bleve/index/scorch.(*Scorch).Batch(0xc00093ea80, 0xc0001df550, 0x0, 0x0)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:356 +0x758
github.com/blevesearch/bleve/index/scorch.(*Scorch).Update(0xc00093ea80, 0xc000975280, 0x5c1ae40, 0xc001106fc0)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:275 +0xd0
github.com/blevesearch/bleve.(*indexImpl).Index(0xc0002e20e0, 0xc000b60750, 0xb, 0x5c1ae40, 0xc001106fc0, 0x0, 0x0)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index_impl.go:257 +0x21e

goroutine 130 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc0000c7500)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 131 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc0000c7500)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 168 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc0006a8700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121


goroutine 16 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc0000c7500)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 166 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc0006a8700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 167 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc0006a8700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 63 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc000847880)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 146 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc000912000)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 147 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc000912000)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 148 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc000912000)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 162 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc0008fe380)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 163 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc0008fe380)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 164 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc0008fe380)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 155 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc0002ef880)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 52 [select]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc0007c8380)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 53 [select]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc0007c8380)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 55 [select]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc00093ea80)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 154 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc0002ef880)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 178 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc000940000)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 179 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc000940000)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 180 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc000940000)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 182 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc000846700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 153 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc0002ef880)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 183 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc000846700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 184 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc000846700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 56 [select]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).pausePersisterForMergerCatchUp(0xc00093ea80, 0x40, 0x3e, 0x0, 0x0, 0x0, 0xc0007de0e0, 0x1, 0x0, 0x0, ...)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:212 +0x461
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc00093ea80)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:85 +0x4a3
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 57 [select]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc00093ea80)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 59 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc0008fe700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 60 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc0008fe700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 61 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc0008fe700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 64 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc000847880)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 36 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc0007c8700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 37 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc0007c8700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 38 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc0007c8700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 133 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc000912700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 134 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc000912700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 135 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc000912700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 157 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc0008fea80)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 158 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc0008fea80)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 159 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc0008fea80)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 137 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc000912a80)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 187 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc000940380)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 188 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc000940380)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 189 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc000940380)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 194 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc0002ee700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 195 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc0002ee700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 196 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc0002ee700)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 116 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc00093ee00)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 117 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc00093ee00)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 118 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc00093ee00)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 198 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc0002ef500)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 65 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc000847880)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 41 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop(0xc0007c8e00)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:58 +0x2ec
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:165 +0x89

goroutine 42 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc0007c8e00)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 43 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc0007c8e00)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 199 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc0002ef500)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 200 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc0002ef500)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121

goroutine 138 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0xc000912a80)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:167 +0x9ce
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:169 +0xe8

goroutine 139 [select, 1 minutes]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc000912a80)
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/merge.go:96 +0x5ba
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	/Users/aviad/demisto/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:171 +0x121
```

**Comment by aviadl** [comment]
@abhinavdangeti Looks much better now.
I think we can close the issue, i will further check and keep you updated
